### ISSUE TITLE
Update test mocks to deal with Django 1.7's registry

### ISSUE THREAD

**Issue by acdha** [django-haystack/django-haystack#1069]
Currently two tests fail because they rely on mock models which aren't registered:

```
======================================================================
ERROR: test_missing_object (test_haystack.test_models.SearchResultTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/toastdriven/django-haystack/test_haystack/test_models.py", line 137, in test_missing_object
    self.assertEqual(awol2.model, None)
  File "/home/travis/build/toastdriven/django-haystack/haystack/models.py", line 98, in _get_model
    self._model = models.get_model(self.app_label, self.model_name)
  File "/home/travis/build/toastdriven/django-haystack/.tox/py27-django1.7/lib/python2.7/site-packages/django/db/models/__init__.py", line 54, in alias
    return getattr(loading, function_name)(*args, **kwargs)
  File "/home/travis/build/toastdriven/django-haystack/.tox/py27-django1.7/lib/python2.7/site-packages/django/apps/registry.py", line 202, in get_model
    return self.get_app_config(app_label).get_model(model_name.lower())
  File "/home/travis/build/toastdriven/django-haystack/.tox/py27-django1.7/lib/python2.7/site-packages/django/apps/config.py", line 161, in get_model
    "App '%s' doesn't have a '%s' model." % (self.label, model_name))
LookupError: App 'core' doesn't have a 'yetanothermockmodel' model.
-------------------- >> begin captured logging << --------------------
haystack: ERROR: Object could not be found in database for SearchResult '<SearchResult: core.mockmodel (pk='1000000')>'.
--------------------- >> end captured logging << ---------------------
======================================================================
FAIL: test_more_like_this_for_model (test_haystack.solr_tests.test_templatetags.MoreLikeThisTagTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/toastdriven/django-haystack/mock-1.0.1-py2.7.egg/mock.py", line 1201, in patched
    return func(*args, **keywargs)
  File "/home/travis/build/toastdriven/django-haystack/test_haystack/solr_tests/test_templatetags.py", line 55, in test_more_like_this_for_model
    any_order=True)
  File "/home/travis/build/toastdriven/django-haystack/mock-1.0.1-py2.7.egg/mock.py", line 877, in assert_has_calls
    '%r not all found in call list' % (tuple(not_found),)
AssertionError: (call().models().more_like_this(<MockModel: daniel3>),) not all found in call list
```

We can probably register these but it's cleaner long-term if we can replace them with normal Django models so we don't need to worry about future changes to Django internals

**Comment by troygrosfield** [comment]
The first part of this test is fixed with the following commit:

- https://github.com/troygrosfield/django-haystack/commit/99fb66283bcfe73722f11c9d7517c74efc52ac68

Inside of PR #1130.

**Comment by simonsmiley** [comment]
Since builds are passing, and django 1.7 is no longer supported, I guess this issue can be closed
