### ISSUE TITLE
Possible problems of recursion.

### ISSUE THREAD

**Issue by alexsilva** [django-haystack/django-haystack#1079]
Version
Haystack: 2.1.1-dev
Celery: 3.1.13
Python 2.7
Django 1.6.1

Using: celery_haystack

python manage.py celery worker -B -l info

Whenever I run the above command

Results in the following error:

```
user@user-pc:~/project$ python manage.py celery worker -B -l info
Traceback (most recent call last):
  File "manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/package/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/package/django/core/management/__init__.py", line 392, in execute'
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/package/djcelery/management/commands/celery.py", line 24, in run_from_argv
    ['{0[0]} {0[1]}'.format(argv)] + argv[2:],
  File "/package/celery/bin/celery.py", line 769, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/package/celery/bin/base.py", line 307, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/package/celery/bin/celery.py", line 761, in handle_argv
    return self.execute(command, argv)
  File "/package/celery/bin/celery.py", line 693, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/package/celery/bin/worker.py", line 179, in run_from_argv
    return self(*args, **options)
  File "/package/celery/bin/base.py", line 270, in __call__
    ret = self.run(*args, **kwargs)
  File "/package/celery/bin/worker.py", line 212, in run
    state_db=self.node_format(state_db, hostname), **kwargs
  File "/package/celery/worker/__init__.py", line 95, in __init__
    self.app.loader.init_worker()
  File "/package/celery/loaders/base.py", line 128, in init_worker
    self.import_default_modules()
  File "/package/djcelery/loaders.py", line 141, in import_default_modules
    self.autodiscover()
  File "/package/djcelery/loaders.py", line 144, in autodiscover
    self.task_modules.update(mod.__name__ for mod in autodiscover() or ())
  File "/package/djcelery/loaders.py", line 179, in autodiscover
    for app in settings.INSTALLED_APPS])
  File "/package/djcelery/loaders.py", line 203, in find_related_module
    return importlib.import_module('{0}.{1}'.format(app, related_name))
  File "/package/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/package/celery_haystack/tasks.py", line 5, in <module>
    from .conf import settings
  File "/package/celery_haystack/conf.py", line 3, in <module>
    from haystack import constants, __version__ as haystack_version
  File "/package/haystack/__init__.py", line 6, in <module>
    from haystack import signals
ImportError: cannot import name signals
```

**Comment by darkpixel** [comment]
I get a similar error on a project that's been in production for about a year after recently typing ```pip install django==1.8``` (Previously running 1.7.x)

```
09:01:15 [aaron@ender:~/code/uitintranet] [uitintranet] develop(+1/-1)+* ± python manage.py runserver
WARNING 2015-04-04 09:01:20,793 importlib 10750 140422165276480 /home/aaron/.virtualenvs/uitintranet/local/lib/python2.7/site-packages/debug_toolbar/settings.py:6: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/aaron/.virtualenvs/uitintranet/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/aaron/.virtualenvs/uitintranet/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/home/aaron/.virtualenvs/uitintranet/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/aaron/.virtualenvs/uitintranet/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/aaron/.virtualenvs/uitintranet/local/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/aaron/.virtualenvs/uitintranet/local/lib/python2.7/site-packages/haystack/__init__.py", line 6, in <module>
    from haystack import signals
ImportError: cannot import name signals
```
```
celery-haystack==0.8
django-haystack==2.3.1
```

**Comment by acdha** [comment]
We don't yet support Django 1.8. I would suggest testing with the current master branch for haystack. If that still fails, try importing haystack.signals directly to see what's actually failing with the import error.

**Comment by acdha** [comment]
Unless @toastdriven objects, I'm inclined to say that we should finish 2.4 and after that point start fixing things like this by dropping Python 2.6 support to follow Django's lead. I'm persuaded by @ncoghlan's argument:

http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html

**Comment by darkpixel** [comment]
Will do.  Thanks.
