### ISSUE TITLE
Can't execute update_index if model has ManyToManyField

### ISSUE THREAD

**Issue by Znack** [django-haystack/django-haystack#1106]
After upgrading django to 1.7 I can't execute management command update_index.

```
Traceback (most recent call last):
  File "/opt/pycharm-3.4.1/helpers/pydev/pydevd.py", line 1733, in <module>
    debugger.run(setup['file'], None, None)
  File "/opt/pycharm-3.4.1/helpers/pydev/pydevd.py", line 1226, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/tochium/projects/povary/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/tochium/projects/povary/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/tochium/projects/povary/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/tochium/projects/povary/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/tochium/projects/povary/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/tochium/projects/povary/src/django-haystack/haystack/management/commands/update_index.py", line 184, in handle
    return super(Command, self).handle(*items, **options)
  File "/home/tochium/projects/povary/local/lib/python2.7/site-packages/django/core/management/base.py", line 503, in handle
    label_output = self.handle_label(label, **options)
  File "/home/tochium/projects/povary/src/django-haystack/haystack/management/commands/update_index.py", line 189, in handle_label
    self.update_backend(label, using)
  File "/home/tochium/projects/povary/src/django-haystack/haystack/management/commands/update_index.py", line 234, in update_backend
    do_update(backend, index, qs, start, end, total, self.verbosity)
  File "/home/tochium/projects/povary/src/django-haystack/haystack/management/commands/update_index.py", line 89, in do_update
    backend.update(index, current_qs)
  File "/home/tochium/projects/povary/src/xapian-haystack/xapian_backend.py", line 355, in update
    data = index.full_prepare(obj)
  File "/home/tochium/projects/povary/src/django-haystack/haystack/indexes.py", line 207, in full_prepare
    self.prepared_data = self.prepare(obj)
  File "/home/tochium/projects/povary/src/django-haystack/haystack/indexes.py", line 198, in prepare
    self.prepared_data[field.index_fieldname] = field.prepare(obj)
  File "/home/tochium/projects/povary/src/django-haystack/haystack/fields.py", line 159, in prepare
    return self.convert(super(CharField, self).prepare(obj))
  File "/home/tochium/projects/povary/src/django-haystack/haystack/fields.py", line 106, in prepare
    return current_object()
  File "/home/tochium/projects/povary/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 839, in __call__
    manager = getattr(self.model, kwargs.pop('manager'))
KeyError: u'manager'
```

I use python2.7.6, django 1.7, django-haystack 2.3.1, search engine: xapian 

I think the problem appears because django from 1.7 add method **call** () to ManyRelatedManager and now in file /haystack/fields.py

```
if callable(current_object):
    return current_object()
```

this condition fires.
Thanks.

**Comment by bjacobel** [comment]
Also having this issue with Python 3.4, django-haystack 2.3.1 and Elasticsearch.

**Comment by jdp** [comment]
Same here. Python 2.7.6, Django==1.8, django-haystack==2.3.1, and Whoosh==2.7.0. It happens if I add a search index field with a `model_attr` to a model foreign key or many to many relation.

**Comment by acdha** [comment]
django-haystack 2.3.1 does not officially support Django 1.8. Have you tried testing with the current master branch? That's not complete – see #1137, #1165, #1175 – but would be useful to confirm the status with the changes which have been merged.

**Comment by mitchelljkotler** [comment]
I am seeing this issue as well.  I just updated to the latest master branch and still see this issue.  Is there a known work around?

**Comment by ninjaotoko** [comment]
I am using Django 1.7 and still see the same error

**Comment by szandara** [comment]
Is this issue solved? I currently have the same problem using

Django 1.8, Pysolr 3.3.2 and Django-Haystack@master

**Comment by kmahelona** [comment]
I also have this error. Django 1.7, Haystack 2.4.1, Solr. 
```
Traceback (most recent call last):
  File "/webapp/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 188, in handle_label
    self.update_backend(label, using)
  File "/webapp/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 233, in update_backend
    do_update(backend, index, qs, start, end, total, verbosity=self.verbosity, commit=self.commit)
  File "/webapp/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 96, in do_update
    backend.update(index, current_qs, commit=commit)
  File "/webapp/local/lib/python2.7/site-packages/haystack/backends/solr_backend.py", line 56, in update
    docs.append(index.full_prepare(obj))
  File "/webapp/local/lib/python2.7/site-packages/haystack/indexes.py", line 212, in full_prepare
    self.prepared_data = self.prepare(obj)
  File "/webapp/local/lib/python2.7/site-packages/haystack/indexes.py", line 203, in prepare
    self.prepared_data[field.index_fieldname] = field.prepare(obj)
  File "/webapp/local/lib/python2.7/site-packages/haystack/fields.py", line 360, in prepare
    return self.convert(super(MultiValueField, self).prepare(obj))
  File "/webapp/local/lib/python2.7/site-packages/haystack/fields.py", line 106, in prepare
    return current_object()
  File "/webapp/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 839, in __call__
    manager = getattr(self.model, kwargs.pop('manager'))
KeyError: u'manager'
```

**Comment by jTiKey** [comment]
Is this solvable?

**Comment by tobltobs** [comment]
Is this issue solved? I currently have the same problem using

Django 1.9.4, Woosh and Django-Haystack@master

**Comment by Terr** [comment]
I have [created a test case](https://github.com/Terr/django-haystack/commit/bf7fbad2c1d970ae377884c61688fe2cbb56b134) that will trigger this error.

I also [applied the fix](https://github.com/Terr/django-haystack/commit/4ad89f10d1582c1ea7d670e774a76d91077a6adf) from @jTiKey, but I would like to try and fix it without triggering an exception. Perhaps a `hasattr` for `all` would be enough. I welcome all suggestions.

**Comment by Terr** [comment]
Those of you who have this problem, could you show how your Field definitions / SearchIndexes that have this issue look like?

I would like to add tests for some common use cases, but I can only come up with the most basic one (a `MultiValueField` with a `model_attr`)

**Comment by msapiro** [comment]
I am seeing this issue with Django 1.9.4 and Haystack 2.5.0. See the comments [here](https://gitlab.com/mailman/hyperkitty/commit/e93535dc75a0cb4dedb565cf49f61452e046f175) for more information. I found it necessary to patch haystack/fields.py based on [this](https://github.com/Terr/django-haystack/commit/4ad89f10d1582c1ea7d670e774a76d91077a6adf) as follows:
```
--- git/django-haystack/haystack/fields.py	2016-07-28 16:14:23.124031131 +0000
+++ /usr/local/lib/python2.7/dist-packages/django_haystack-2.5.0-py2.7.egg/haystack/fields.py	2016-07-30 19:39:24.666489705 +0000
@@ -128,7 +128,10 @@
                     )
 
             if callable(current_object):
-                values.append(current_object())
+                try:
+                    values.append(current_object())
+                except KeyError:
+                    values.append(current_object.all())
             else:
                 values.append(current_object)
 
```

**Comment by SteveByerly** [comment]
Can you please show your indexes?

I'm assuming you're using `indexes.CharField` instead of `indexes.MultiValueField`. If you are trying to use the `CharField` with multiple values, you will need to manually prepare them to fit into the one field - e.g. ', '.join([x.name for x in foo.related_objects.all()])

**Comment by msapiro** [comment]
Thank you for the reply. I am not the author of this code. I am a user trying to figure out an issue I'm having. I think the relevant code is
```
from haystack import indexes
from haystack.query import SearchQuerySet
from haystack.management.commands.update_index import \
    Command as UpdateIndexCommand
from hyperkitty.models import Email


class EmailIndex(indexes.SearchIndex, indexes.Indexable):

    text = indexes.CharField(document=True, use_template=True)
    mailinglist = indexes.CharField(model_attr='mailinglist__name')
    subject = indexes.CharField(model_attr='subject', boost=1.25,
                                use_template=True)
    date = indexes.DateTimeField(model_attr='date')
    sender = indexes.CharField(model_attr='sender__name', boost=1.125)
    tags = indexes.CharField(model_attr='thread__tags', boost=1.25)
    archived_date = indexes.DateTimeField(model_attr='archived_date')
```
My issue was created by the addition of the
```
    tags = indexes.CharField(model_attr='thread__tags', boost=1.25)
```
line in the above. Based on your reply, it seems that this should be a `MultiValueField` rather than a `CharField`. I will take it from here with the author of the code. Thanks again.

**Comment by SteveByerly** [comment]
Let me know if this fixes your issue. I will try to update the docs soon.

**Comment by msapiro** [comment]
Simply changing
```
tags = indexes.CharField(model_attr='thread__tags', boost=1.25)
```
to
```
tags = indexes.MultiValueField(model_attr='thread__tags', boost=1.25)
```
is not sufficient to solve the issue. I don't know the underlying application code well enough to go further with it. This is all [reported](https://gitlab.com/mailman/hyperkitty/commit/e93535dc75a0cb4dedb565cf49f61452e046f175) and I am waiting for a response from the HyperKitty maintainer.

**Comment by SteveByerly** [comment]
You still need to specify the attribute on the related model.

Try:
`tags = indexes.MultiValueField(model_attr='thread__tags__name', boost=1.25)`

where `name` is an attribute on the Tag model (could be tag, etc).

**Comment by abompard** [comment]
I'm the author of the hyperkitty code that @msapiro quoted. I confirm that the fix proposed by @SteveByerly works: https://gitlab.com/mailman/hyperkitty/commit/84daf74e83289576d141341d4e0e4acbb8f7a836
(I had to add `null=True` too). Thanks a lot for your help.

**Comment by acdha** [comment]
@abompard Does that mean this issue can be closed?

**Comment by abompard** [comment]
@acdha Neither @msapiro nor me were the original reporters, so I guess it's not up to us. I was just mentioning that the issue raised here by @msapiro is fixed.

**Comment by SteveByerly** [comment]
I'll update the documentation and close this issue and any related.
