### ISSUE TITLE
"Conflicting option string" error when rebuilding index with Django 1.7 and Django Haystack 2.4.0

### ISSUE THREAD

**Issue by ninapavlich** [django-haystack/django-haystack#1164]
I was experiencing the issue described here: 
https://github.com/django-haystack/django-haystack/issues/1097

to work around it, I updated my haystack version to the 2.4.0 pre-release.

Now, when I attempt to rebuild the index, I get a conflict error:

	(venv)➜  example-project git:(master) python manage.py rebuild_index
	Traceback (most recent call last):
		File "manage.py", line 11, in <module>
			execute_from_command_line(sys.argv)
		File "/Users/nina/Documents/Sites/example-project/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
			utility.execute()
		File "/Users/nina/Documents/Sites/example-project/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
			self.fetch_command(subcommand).run_from_argv(self.argv)
		File "/Users/nina/Documents/Sites/example-project/venv/lib/python2.7/site-packages/django/core/management/base.py", line 284, in run_from_argv
			parser = self.create_parser(argv[0], argv[1])
		File "/Users/nina/Documents/Sites/example-project/venv/lib/python2.7/site-packages/django/core/management/base.py", line 265, in create_parser
			option_list=self.option_list)
		File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 1219, in __init__
			add_help=add_help_option)
		File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 1261, in _populate_option_list
			self.add_options(option_list)
		File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 1039, in add_options
			self.add_option(option)
		File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 1020, in add_option
			self._check_conflict(option)
		File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 995, in _check_conflict
			option)
	optparse.OptionConflictError: option --nocommit: conflicting option string(s): --nocommit

My library versions:
Python 2.7.5
Django==1.7.2
-e git+https://github.com/django-haystack/django-haystack.git@866b24f3f7769b569799c063ee6139de78a971bf#egg=django_haystack-v2.4.0

**Comment by ninapavlich** [comment]
I updated to Django==1.8.2 and the latest haystack version (-e git+https://github.com/django-haystack/django-haystack.git@0576c8093caf59bebedce75e0d711aacfd36f03f#egg=django_haystack-origin_HEAD) and this works now.
