### ISSUE TITLE
update() got an unexpected keyword argument 'commit'

### ISSUE THREAD

**Issue by westhomas** [django-haystack/django-haystack#1170]
While attempting to fix #1152 I ran into another issue.

```
$ pip install https://github.com/django-haystack/django-haystack/zipball/e470320da1a9e6e5cc5865066821b5234fecc9be

$ python manage.py rebuild_index
WARNING: This will irreparably remove EVERYTHING from your search index in connection 'default'.
Your choices after this are to restore from backups or rebuild via the `rebuild_index` command.
Are you sure you wish to continue? [y/N] y
Removing all documents from your index because you said so.
All documents removed.
Indexing 85332 articles
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/haystack/management/commands/rebuild_index.py", line 26, in handle
    call_command('update_index', **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 115, in call_command
    return klass.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/haystack/management/commands/update_index.py", line 195, in handle
    return super(Command, self).handle(*items, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 503, in handle
    label_output = self.handle_label(label, **options)
  File "/usr/local/lib/python2.7/dist-packages/haystack/management/commands/update_index.py", line 200, in handle_label
    self.update_backend(label, using)
  File "/usr/local/lib/python2.7/dist-packages/haystack/management/commands/update_index.py", line 245, in update_backend
    do_update(backend, index, qs, start, end, total, verbosity=self.verbosity, commit=self.commit)
  File "/usr/local/lib/python2.7/dist-packages/haystack/management/commands/update_index.py", line 91, in do_update
    backend.update(index, current_qs, commit=commit)
TypeError: update() got an unexpected keyword argument 'commit'
```

Commenting out the commit param on line 91 fixes the issue, but I'm uncertain of the impact of this change.

python2.7
django==1.7.7
xapian-bindings-1.2.12
xapian-core-1.2.12
raven==5.2.0

**Comment by jorgecarleitao** [comment]
This is under consideration in xapian-haystack: https://github.com/notanumber/xapian-haystack/pull/147

**Comment by edgecaselabs** [comment]
I'm getting a similar issue when remove=True is used.  Not sure if the planned fixes cover this too.


/home/ubuntu/.virtualenvs/env/local/lib/python2.7/site-packages/haystack/management/commands/update_index.pyc in do_remove(backend, index, model, pks_seen, start, upper_bound, verbosity, commit)
    109                 print("  removing %s." % result.pk)
    110 
--> 111             backend.remove(".".join([result.app_label, result.model_name, str(result.pk)]), commit=commit)
    112 
    113 

TypeError: remove() got an unexpected keyword argument 'commit'

**Comment by acdha** [comment]
@edgecaselabs Are you also using xapian-haystack and, if so, a recent version of both it and Haystack? Haystack 2.4 shipped with the commit flag and it looks like notanumber/xapian-haystack#147 merged awhile back.

**Comment by asmyshlyaev177** [comment]
Centos 6, django 1.11, django-haystack 2.6.0, xapian-haystack 2.1.0 with Xapian(last version from official website). When try to rebuild index got same:


```
Indexing 6 posts
.0.0
x[ERROR/MainProcess] Failed indexing 1 - 6 (retry 5/5): update() got an unexpected keyword argument 'commit' (pid 15369): update() got an unexpected keyword argument 'commit'
Traceback (most recent call last):
  File "/root/myblog/lib/python3.5/site-packages/haystack/management/commands/update_index.py", line 84, in do_update
    backend.update(index, current_qs, commit=commit)
TypeError: update() got an unexpected keyword argument 'commit'
[ERROR/MainProcess] Error updating blog using default
Traceback (most recent call last):
  File "/root/myblog/lib/python3.5/site-packages/haystack/management/commands/update_index.py", line 214, in handle
    self.update_backend(label, using)
  File "/root/myblog/lib/python3.5/site-packages/haystack/management/commands/update_index.py", line 257, in update_backend
    commit=self.commit, max_retries=self.max_retries)
  File "/root/myblog/lib/python3.5/site-packages/haystack/management/commands/update_index.py", line 84, in do_update
    backend.update(index, current_qs, commit=commit)
TypeError: update() got an unexpected keyword argument 'commit'
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/root/myblog/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/root/myblog/lib/python3.5/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/myblog/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/myblog/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/root/myblog/lib/python3.5/site-packages/haystack/management/commands/rebuild_index.py", line 37, in handle
    call_command('update_index', **options)
  File "/root/myblog/lib/python3.5/site-packages/django/core/management/__init__.py", line 130, in call_command
    return command.execute(*args, **defaults)
  File "/root/myblog/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/root/myblog/lib/python3.5/site-packages/haystack/management/commands/update_index.py", line 214, in handle
    self.update_backend(label, using)
  File "/root/myblog/lib/python3.5/site-packages/haystack/management/commands/update_index.py", line 257, in update_backend
    commit=self.commit, max_retries=self.max_retries)
  File "/root/myblog/lib/python3.5/site-packages/haystack/management/commands/update_index.py", line 84, in do_update
    backend.update(index, current_qs, commit=commit)
TypeError: update() got an unexpected keyword argument 'commit'
```

**Comment by acdha** [comment]
@asmyshlyaev177 See the previous comment in this issue - this should be reported against xapian-haystack. It looks like they had a commit in https://github.com/notanumber/xapian-haystack/commit/d3f1e011da3d9bebd88c78fe7a87cd6171ae650c which broke the earlier https://github.com/notanumber/xapian-haystack/pull/147
