### ISSUE TITLE
Haystack + Whoosh throwing root:Error updating <appname> using default

### ISSUE THREAD

**Issue by davegri** [django-haystack/django-haystack#1248]
Django 1.8.4

django-haystack 2.4.0

Whoosh 2.7.0

    python manage.py rebuild_index                                                                                                                                     ⏎ master ✖ ✱ ◼
    
    WARNING: This will irreparably remove EVERYTHING from your search index in connection 'default'.
    Your choices after this are to restore from backups or rebuild via the `rebuild_index` command.
    Are you sure you wish to continue? [y/N] y
    Removing all documents from your index because you said so.
    All documents removed.
    Indexing 1934 images
    ERROR:root:Error updating crawlers using default 
    Traceback (most recent call last):
      File "/home/david/.virtualenvs/stocksearch/lib/python3.4/site-packages/haystack/management/commands/update_index.py", line 188, in handle_label
        self.update_backend(label, using)
      File "/home/david/.virtualenvs/stocksearch/lib/python3.4/site-packages/haystack/management/commands/update_index.py", line 233, in update_backend
        do_update(backend, index, qs, start, end, total, verbosity=self.verbosity, commit=self.commit)
      File "/home/david/.virtualenvs/stocksearch/lib/python3.4/site-packages/haystack/management/commands/update_index.py", line 96, in do_update
        backend.update(index, current_qs, commit=commit)
      File "/home/david/.virtualenvs/stocksearch/lib/python3.4/site-packages/haystack/backends/whoosh_backend.py", line 196, in update
        doc = index.full_prepare(obj)
      File "/home/david/.virtualenvs/stocksearch/lib/python3.4/site-packages/haystack/indexes.py", line 212, in full_prepare
        self.prepared_data = self.prepare(obj)
      File "/home/david/.virtualenvs/stocksearch/lib/python3.4/site-packages/haystack/indexes.py", line 203, in prepare
        self.prepared_data[field.index_fieldname] = field.prepare(obj)
      File "/home/david/.virtualenvs/stocksearch/lib/python3.4/site-packages/haystack/fields.py", line 159, in prepare
        return self.convert(super(CharField, self).prepare(obj))
      File "/home/david/.virtualenvs/stocksearch/lib/python3.4/site-packages/haystack/fields.py", line 106, in prepare
        return current_object()
      File "/home/david/.virtualenvs/stocksearch/lib/python3.4/site-packages/django/db/models/fields/related.py", line 888, in __call__
        manager = getattr(self.model, kwargs.pop('manager'))
    KeyError: 'manager'
    Traceback (most recent call last):
      File "manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/home/david/.virtualenvs/stocksearch/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
        utility.execute()
      File "/home/david/.virtualenvs/stocksearch/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/home/david/.virtualenvs/stocksearch/lib/python3.4/site-packages/django/core/management/base.py", line 393, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/home/david/.virtualenvs/stocksearch/lib/python3.4/site-packages/django/core/management/base.py", line 444, in execute
        output = self.handle(*args, **options)
      File "/home/david/.virtualenvs/stocksearch/lib/python3.4/site-packages/haystack/management/commands/rebuild_index.py", line 26, in handle
        call_command('update_index', **options)
      File "/home/david/.virtualenvs/stocksearch/lib/python3.4/site-packages/django/core/management/__init__.py", line 120, in call_command
        return command.execute(*args, **defaults)
      File "/home/david/.virtualenvs/stocksearch/lib/python3.4/site-packages/django/core/management/base.py", line 444, in execute
        output = self.handle(*args, **options)
      File "/home/david/.virtualenvs/stocksearch/lib/python3.4/site-packages/haystack/management/commands/update_index.py", line 183, in handle
        return super(Command, self).handle(*items, **options)
      File "/home/david/.virtualenvs/stocksearch/lib/python3.4/site-packages/django/core/management/base.py", line 622, in handle
        label_output = self.handle_label(label, **options)
      File "/home/david/.virtualenvs/stocksearch/lib/python3.4/site-packages/haystack/management/commands/update_index.py", line 188, in handle_label
        self.update_backend(label, using)
      File "/home/david/.virtualenvs/stocksearch/lib/python3.4/site-packages/haystack/management/commands/update_index.py", line 233, in update_backend
        do_update(backend, index, qs, start, end, total, verbosity=self.verbosity, commit=self.commit)
      File "/home/david/.virtualenvs/stocksearch/lib/python3.4/site-packages/haystack/management/commands/update_index.py", line 96, in do_update
        backend.update(index, current_qs, commit=commit)
      File "/home/david/.virtualenvs/stocksearch/lib/python3.4/site-packages/haystack/backends/whoosh_backend.py", line 196, in update
        doc = index.full_prepare(obj)
      File "/home/david/.virtualenvs/stocksearch/lib/python3.4/site-packages/haystack/indexes.py", line 212, in full_prepare
        self.prepared_data = self.prepare(obj)
      File "/home/david/.virtualenvs/stocksearch/lib/python3.4/site-packages/haystack/indexes.py", line 203, in prepare
        self.prepared_data[field.index_fieldname] = field.prepare(obj)
      File "/home/david/.virtualenvs/stocksearch/lib/python3.4/site-packages/haystack/fields.py", line 159, in prepare
        return self.convert(super(CharField, self).prepare(obj))
      File "/home/david/.virtualenvs/stocksearch/lib/python3.4/site-packages/haystack/fields.py", line 106, in prepare
        return current_object()
      File "/home/david/.virtualenvs/stocksearch/lib/python3.4/site-packages/django/db/models/fields/related.py", line 888, in __call__
        manager = getattr(self.model, kwargs.pop('manager'))
    KeyError: 'manager'

**Comment by acdha** [comment]
Do you have a reproducible testcase for this? Based on the code in https://github.com/django-haystack/django-haystack/blob/6b61dc0b4c002cf97e6aa96f0e6308513040d060/haystack/fields.py#L82-L106 I'm assuming this has something to do with resolving `__` references in your `model_attr` setting.

**Comment by 20083017** [comment]
seems you have a foreignkey in search indexes， remove that is one of the solutions ! just happen to meet the same problem!
