### ISSUE TITLE
rebuild index error AttributeError: 'UnknownFieldError' object has no attribute '__name__'

### ISSUE THREAD

**Issue by TheDrifter254** [django-haystack/django-haystack#1273]
I upgraded from django 1.5 to 1.7 and all its packages to the latest version. Now using haystack 2.0.0 and when I tried to run stackoverflow.com/questions/33755118 previously had to include django markup deprecated to get it past the previous error. Now i'm getting the unknown field error 

```
   Traceback (most recent call last):
    File "manage.py", line 11, in <module>
      execute_from_command_line(sys.argv)
    File "/home/kbuzz/webapps/kenyabuzz/lib/python2.7/Django-1.7.10-py2.7.egg/django/core/management/__init__.py", line 385, in execute_from_command_line
      utility.execute()
    File "/home/kbuzz/webapps/kenyabuzz/lib/python2.7/Django-1.7.10-py2.7.egg/django/core/management/__init__.py", line 377, in execute
      self.fetch_command(subcommand).run_from_argv(self.argv)
    File "/home/kbuzz/webapps/kenyabuzz/lib/python2.7/Django-1.7.10-py2.7.egg/django/core/management/base.py", line 288, in run_from_argv
      self.execute(*args, **options.__dict__)
    File "/home/kbuzz/webapps/kenyabuzz/lib/python2.7/Django-1.7.10-py2.7.egg/django/core/management/base.py", line 338, in execute
      output = self.handle(*args, **options)
    File "/home/kbuzz/lib/python2.7/haystack/management/commands/rebuild_index.py", line 15, in handle
      call_command('update_index', **options)
    File "/home/kbuzz/webapps/kenyabuzz/lib/python2.7/Django-1.7.10-py2.7.egg/django/core/management/__init__.py", line 115, in call_command
      return klass.execute(*args, **defaults)
    File "/home/kbuzz/webapps/kenyabuzz/lib/python2.7/Django-1.7.10-py2.7.egg/django/core/management/base.py", line 338, in execute
      output = self.handle(*args, **options)
    File "/home/kbuzz/lib/python2.7/haystack/management/commands/update_index.py", line 184, in handle
      return super(Command, self).handle(*items, **options)
    File "/home/kbuzz/webapps/kenyabuzz/lib/python2.7/Django-1.7.10-py2.7.egg/django/core/management/base.py", line 503, in handle
      label_output = self.handle_label(label, **options)
    File "/home/kbuzz/lib/python2.7/haystack/management/commands/update_index.py", line 210, in handle_label
      self.update_backend(label, using)
    File "/home/kbuzz/lib/python2.7/haystack/management/commands/update_index.py", line 256, in update_backend
      do_update(backend, index, qs, start, end, total, self.verbosity)
    File "/home/kbuzz/lib/python2.7/haystack/management/commands/update_index.py", line 78, in do_update
      backend.update(index, current_qs)
    File "/home/kbuzz/lib/python2.7/haystack/backends/whoosh_backend.py", line 189, in update
      self.log.error(u"%s while preparing object for update" % e.__name__, exc_info=True, extra={
  AttributeError: 'UnknownFieldError' object has no attribute '__name__'
```

**Comment by acdha** [comment]
Have you tried upgrading to Haystack 2.4.1? The error handling code now looks like this:

https://github.com/django-haystack/django-haystack/blob/master/haystack/backends/whoosh_backend.py#L218-L220

The change goes back to this commit, which you could cherry-pick if you have some reason preventing you from upgrading to a current version of Haystack but I would recommend against that since there have been many other bugs fixed as well since then:

https://github.com/django-haystack/django-haystack/commit/3cdb2570f0961a80aff8f313c33d0b50a1a2242b
