### ISSUE TITLE
Django Haystack & Whoosh error AttributeError: 'UnknownFieldError' object has no attribute '__name__'

### ISSUE THREAD

**Issue by Six-wars** [django-haystack/django-haystack#1274]
I've added the question to stackoverflow, http://stackoverflow.com/questions/33804525/django-haystack-whoosh-error-attributeerror-unknownfielderror-object-has-no also copied the description below

I've got Django setup (1.7, previously 1.5) with the following in the settings file
```
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
        'PATH': '/home/kbuzz/whoosh_index',
        'EXCLUDED_INDEXES': ['<movies.search_indexes.EventIndex object at 0x7f445fff0ef0>','<movies.search_indexes.EventIndex object at 0x7fd07ca3ef58>','<movies.search_indexes.EventIndex object at 0x7f0d2cfecf58>','<movies.search_indexes.EventIndex object at 0x7f990700bf58>'],
    },
}
````

I've tried running rebuild_index and clear_index then update_index but I get this error

```
  Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/home/kbuzz/webapps/kenyabuzz/lib/python2.7/Django-1.7.10-py2.7.egg/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/kbuzz/webapps/kenyabuzz/lib/python2.7/Django-1.7.10-py2.7.egg/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/kbuzz/webapps/kenyabuzz/lib/python2.7/Django-1.7.10-py2.7.egg/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/kbuzz/webapps/kenyabuzz/lib/python2.7/Django-1.7.10-py2.7.egg/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/kbuzz/lib/python2.7/haystack/management/commands/rebuild_index.py", line 15, in handle
    call_command('update_index', **options)
  File "/home/kbuzz/webapps/kenyabuzz/lib/python2.7/Django-1.7.10-py2.7.egg/django/core/management/__init__.py", line 115, in call_command
    return klass.execute(*args, **defaults)
  File "/home/kbuzz/webapps/kenyabuzz/lib/python2.7/Django-1.7.10-py2.7.egg/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/kbuzz/lib/python2.7/haystack/management/commands/update_index.py", line 184, in handle
    return super(Command, self).handle(*items, **options)
  File "/home/kbuzz/webapps/kenyabuzz/lib/python2.7/Django-1.7.10-py2.7.egg/django/core/management/base.py", line 503, in handle
    label_output = self.handle_label(label, **options)
  File "/home/kbuzz/lib/python2.7/haystack/management/commands/update_index.py", line 210, in handle_label
    self.update_backend(label, using)
  File "/home/kbuzz/lib/python2.7/haystack/management/commands/update_index.py", line 256, in update_backend
    do_update(backend, index, qs, start, end, total, self.verbosity)
  File "/home/kbuzz/lib/python2.7/haystack/management/commands/update_index.py", line 78, in do_update
    backend.update(index, current_qs)
  File "/home/kbuzz/lib/python2.7/haystack/backends/whoosh_backend.py", line 189, in update
    self.log.error(u"%s while preparing object for update" % e.__name__, exc_info=True, extra={
AttributeError: 'UnknownFieldError' object has no attribute '__name__'
```

before it are incompatibility error which doesn't cause an issue for clear_index and migrations below but I doubt this causes the error.

```
WARNING: This will irreparably remove EVERYTHING from your search index in connection 'default'
Your choices after this are to restore from backups or rebuild via the `rebuild_index` command.
Are you sure you wish to continue? [y/N] y

Removing all documents from your index because you said so.
All documents removed.
[kbuzz@web306 kb]$ python2.7 manage.py update_index
/home/kbuzz/webapps/django/lib/python2.7/mptt/managers.py:43: RemovedInDjango18Warning: `TreeManager.get_query_set` method should be renamed `get_queryset`.
  class TreeManager(models.Manager):

/home/kbuzz/webapps/django/lib/python2.7/mptt/admin.py:20: RemovedInDjango18Warning: `MPTTChangeList.get_query_set` method should be renamed `get_queryset`.
  class MPTTChangeList(ChangeList):

/home/kbuzz/webapps/django/lib/python2.7/mptt/managers.py:181: RemovedInDjango18Warning: `BaseManager.get_query_set` is deprecated, use `get_queryset` instead.
  return super(TreeManager, self).get_query_set().order_by(

/home/kbuzz/webapps/django/lib/python2.7/autocomplete_light/forms.py:266: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form ModelForm needs updating
  attrs)

/home/kbuzz/webapps/django/lib/python2.7/autocomplete_light/forms.py:448: RemovedInDjango18Warning: Calling modelform_factory without defining 'fields' or 'exclude' explicitly is deprecated
  return django_modelform_factory(model, **kwargs)

/home/kbuzz/webapps/django/lib/python2.7/autocomplete_light/forms.py:266: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form CategoryForm needs updating
  attrs)

/home/kbuzz/webapps/django/lib/python2.7/autocomplete_light/forms.py:266: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form AreaForm needs updating
  attrs)

/home/kbuzz/webapps/django/lib/python2.7/autocomplete_light/forms.py:266: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form ArticleForm needs updating
  attrs)

/home/kbuzz/webapps/django/lib/python2.7/autocomplete_light/forms.py:266: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form BannerForm needs updating
  attrs)

/home/kbuzz/webapps/django/lib/python2.7/autocomplete_light/forms.py:266: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form VenueForm needs updating
  attrs)

/home/kbuzz/webapps/kenyabuzz/lib/python2.7/Django-1.7.10-py2.7.egg/django/forms/widgets.py:143: RemovedInDjango18Warning: `VenueShowInline.queryset` method should be renamed `get_queryset`.
  .__new__(mcs, name, bases, attrs))

/home/kbuzz/webapps/kenyabuzz/lib/python2.7/Django-1.7.10-py2.7.egg/django/forms/widgets.py:143: RemovedInDjango18Warning: `VenueShowAdmin.queryset` method should be renamed `get_queryset`.
  .__new__(mcs, name, bases, attrs))

/home/kbuzz/webapps/kenyabuzz/lib/python2.7/Django-1.7.10-py2.7.egg/django/forms/widgets.py:143: RemovedInDjango18Warning: `EventDateInline.queryset` method should be renamed `get_queryset`.
  .__new__(mcs, name, bases, attrs))

/home/kbuzz/webapps/django/lib/python2.7/autocomplete_light/forms.py:266: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form EventForm needs updating
  attrs)

/home/kbuzz/webapps/django/lib/python2.7/autocomplete_light/forms.py:266: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form RecurringEventForm needs updating
  attrs)

/home/kbuzz/webapps/django/lib/python2.7/autocomplete_light/forms.py:266: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form GalleryForm needs updating
  attrs)

/home/kbuzz/webapps/django/lib/python2.7/autocomplete_light/forms.py:266: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form EntryForm needs updating
  attrs)

/home/kbuzz/webapps/kenyabuzz/lib/python2.7/Django-1.7.10-py2.7.egg/django/forms/widgets.py:143: RemovedInDjango18Warning: `MovieShowInline2.queryset` method should be renamed `get_queryset`.
  .__new__(mcs, name, bases, attrs))

/home/kbuzz/webapps/kenyabuzz/lib/python2.7/Django-1.7.10-py2.7.egg/django/forms/widgets.py:143: RemovedInDjango18Warning: `MovieShowInline.queryset` method should be renamed `get_queryset`.
  .__new__(mcs, name, bases, attrs))

/home/kbuzz/webapps/django/lib/python2.7/autocomplete_light/forms.py:266: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form MovieForm needs updating
  attrs)

/home/kbuzz/webapps/kenyabuzz/kb/profiles/forms.py:82: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form CustomUserChangeForm needs updating
  class CustomUserChangeForm(forms.ModelForm):

System check identified some issues:

WARNINGS:
?: (1_6.W001) Some project unittests may not execute as expected.
  HINT: Django 1.6 introduced a new default test runner. It looks like this project was generated using Django 1.5 or earlier. You should ensure your tests are all running & behaving as expected. See https://docs.djangoproject.com/en/dev/releases/1.6/#new-test-runner for more information.
events.Event.free: (1_6.W002) BooleanField does not have a default value.
  HINT: Django 1.6 changed the default value of BooleanField from False to None. See https://docs.djangoproject.com/en/1.6/ref/models/fields/#booleanfield for more information.
events.Event.jkia_ad: (1_6.W002) BooleanField does not have a default value.
  HINT: Django 1.6 changed the default value of BooleanField from False to None. See https://docs.djangoproject.com/en/1.6/ref/models/fields/#booleanfield for more information.
events.Event.taxi: (1_6.W002) BooleanField does not have a default value.
  HINT: Django 1.6 changed the default value of BooleanField from False to None. See https://docs.djangoproject.com/en/1.6/ref/models/fields/#booleanfield for more information.
Indexing 5005 articles
/home/kbuzz/lib/python2.7/haystack/utils/__init__.py:26: RemovedInDjango18Warning: Options.module_name has been deprecated in favor of model_name
  return u"%s.%s.%s" % (obj_or_string._meta.app_label, obj_or_string._meta.module_name, obj_or_string._get_pk_val())

/home/kbuzz/lib/python2.7/haystack/indexes.py:180: RemovedInDjango18Warning: Options.module_name has been deprecated in favor of model_name
  DJANGO_CT: "%s.%s" % (obj._meta.app_label, obj._meta.module_name),

/home/kbuzz/lib/python2.7/haystack/fields.py:127: RemovedInDjango18Warning: Options.module_name has been deprecated in favor of model_name
  template_names = ['search/indexes/%s/%s_%s.txt' % (obj._meta.app_label, obj._meta.module_name, self.instance_name)]

/home/kbuzz/webapps/kenyabuzz/kb/events/forms.py:66: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form ImageForm needs updating
  class ImageForm(ModelForm):

/home/kbuzz/webapps/kenyabuzz/kb/events/forms.py:80: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form EventDateForm needs updating
  class EventDateForm(ModelForm):
```
I can include models if needed but I assume since migrate works they're not related. I'm using whoosh 2.4.1 and haystack 2.0.0

**Comment by sampeka** [comment]
Hi @Six-wars, are you still experiencing this problem? If so, could you try updating to haystack 2.4 and see if the issue still persists?

**Comment by Six-wars** [comment]
It's now working for me, thanks you, took a lot of debugging though
