### ISSUE TITLE
KeyError: u'_source' with update_index management command

### ISSUE THREAD

**Issue by muhammad-ammar** [django-haystack/django-haystack#1279]
Upon executing `python manage.py update_index --remove`, i am getting the below issue

```
ERROR:root:Error updating v1 using default 
Traceback (most recent call last):
  File "/ma/src/notes-venv/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 188, in handle_label
    self.update_backend(label, using)
  File "/ma/src/notes-venv/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 276, in update_backend
    for pk, rec_id in index_pks[start:upper_bound]:
  File "/ma/src/notes-venv/local/lib/python2.7/site-packages/haystack/query.py", line 272, in __getitem__
    self._fill_cache(start, bound)
  File "/ma/src/notes-venv/local/lib/python2.7/site-packages/haystack/query.py", line 636, in _fill_cache
    return super(ValuesListSearchQuerySet, self)._fill_cache(start, end, **kwargs)
  File "/ma/src/notes-venv/local/lib/python2.7/site-packages/haystack/query.py", line 171, in _fill_cache
    results = self.query.get_results(**kwargs)
  File "/ma/src/notes-venv/local/lib/python2.7/site-packages/haystack/backends/__init__.py", line 645, in get_results
    self.run(**kwargs)
  File "/ma/src/notes-venv/local/lib/python2.7/site-packages/haystack/backends/elasticsearch_backend.py", line 924, in run
    results = self.backend.search(final_query, **search_kwargs)
  File "/ma/src/notes-venv/local/lib/python2.7/site-packages/haystack/backends/__init__.py", line 35, in wrapper
    return func(obj, query_string, *args, **kwargs)
  File "/ma/src/notes-venv/local/lib/python2.7/site-packages/haystack/backends/elasticsearch_backend.py", line 528, in search
    geo_sort=geo_sort)
  File "/ma/src/ma-notes-api/notesserver/highlight.py", line 57, in _process_results
    raw_results, highlight, result_class, distance_point, geo_sort
  File "/ma/src/notes-venv/local/lib/python2.7/site-packages/haystack/backends/elasticsearch_backend.py", line 605, in _process_results
    source = raw_result['_source']
KeyError: u'_source'
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/ma/src/notes-venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/ma/src/notes-venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/ma/src/notes-venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/ma/src/notes-venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/ma/src/notes-venv/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 183, in handle
    return super(Command, self).handle(*items, **options)
  File "/ma/src/notes-venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 623, in handle
    label_output = self.handle_label(label, **options)
  File "/ma/src/notes-venv/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 188, in handle_label
    self.update_backend(label, using)
  File "/ma/src/notes-venv/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 276, in update_backend
    for pk, rec_id in index_pks[start:upper_bound]:
  File "/ma/src/notes-venv/local/lib/python2.7/site-packages/haystack/query.py", line 272, in __getitem__
    self._fill_cache(start, bound)
  File "/ma/src/notes-venv/local/lib/python2.7/site-packages/haystack/query.py", line 636, in _fill_cache
    return super(ValuesListSearchQuerySet, self)._fill_cache(start, end, **kwargs)
  File "/ma/src/notes-venv/local/lib/python2.7/site-packages/haystack/query.py", line 171, in _fill_cache
    results = self.query.get_results(**kwargs)
  File "/ma/src/notes-venv/local/lib/python2.7/site-packages/haystack/backends/__init__.py", line 645, in get_results
    self.run(**kwargs)
  File "/ma/src/notes-venv/local/lib/python2.7/site-packages/haystack/backends/elasticsearch_backend.py", line 924, in run
    results = self.backend.search(final_query, **search_kwargs)
  File "/ma/src/notes-venv/local/lib/python2.7/site-packages/haystack/backends/__init__.py", line 35, in wrapper
    return func(obj, query_string, *args, **kwargs)
  File "/ma/src/notes-venv/local/lib/python2.7/site-packages/haystack/backends/elasticsearch_backend.py", line 528, in search
    geo_sort=geo_sort)
  File "/ma/src/ma-notes-api/notesserver/highlight.py", line 57, in _process_results
    raw_results, highlight, result_class, distance_point, geo_sort
  File "/ma/src/notes-venv/local/lib/python2.7/site-packages/haystack/backends/elasticsearch_backend.py", line 605, in _process_results
    source = raw_result['_source']
KeyError: u'_source'
```

Packages
- Django==1.8.5
- django-haystack==2.4.1
- elasticsearch==0.4.5
- Elastic Search version 0.90.11

Note: 
- Downgrading django-haystack to 2.3.1 solves the issue.
- Everything works fine if i use Elastic Search version 1.4.2

**Comment by sampeka** [comment]
Docs indicate that 0.90+ is supported, backwards support has probably been broken at some point and the documentation hasn't been updated yet to reflect this

**Comment by aliceh75** [comment]
The docs at http://django-haystack.readthedocs.io/en/v2.4.1/backend_support.html suggest ElasticSearch 1.0+ is required (so this issue should probably be closed)

**Comment by muhammad-ammar** [comment]
Thanks everyone for your time and help. I am closing this issue.
