### ISSUE TITLE
Django 1.9 AppRegistryNotReady exception

### ISSUE THREAD

**Issue by manikos** [django-haystack/django-haystack#1282]
Hello to everyone.
today I upgraded to django 1.9 and faced an exception which occurs only when django-haystack is in `INSTALLED_APPS`. As long as I remove it from there, the exception is gone.
Here is the traceback:

```
bash -cl "/home/nick/.virtualenvs/mosxou_env_2/bin/python /usr/bin/pycharm-4.0.6/helpers/pycharm/django_manage.py runserver /home/nick/django_projects/giteftra_shop"
Traceback (most recent call last):
  File "/usr/bin/pycharm-4.0.6/helpers/pycharm/django_manage.py", line 41, in <module>
    run_module(manage_file, None, '__main__', True)
  File "/usr/lib/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/nick/django_projects/giteftra_shop/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/nick/.virtualenvs/mosxou_env_2/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/home/nick/.virtualenvs/mosxou_env_2/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/nick/.virtualenvs/mosxou_env_2/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 176, in fetch_command
    commands = get_commands()
  File "/home/nick/.virtualenvs/mosxou_env_2/local/lib/python2.7/site-packages/django/utils/lru_cache.py", line 100, in wrapper
    result = user_function(*args, **kwds)
  File "/home/nick/.virtualenvs/mosxou_env_2/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 71, in get_commands
    for app_config in reversed(list(apps.get_app_configs())):
  File "/home/nick/.virtualenvs/mosxou_env_2/local/lib/python2.7/site-packages/django/apps/registry.py", line 137, in get_app_configs
    self.check_apps_ready()
  File "/home/nick/.virtualenvs/mosxou_env_2/local/lib/python2.7/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

Process finished with exit code 1
```

Here is the list of my `INSTALLED_APPS`:
```
MODELTRANSLATION_APP = ('modeltranslation', )  # used for translation of models inside the db. Must go 1st in list!

DJANGO_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.flatpages',
)

THIRD_PARTY_APPS = (
    'mptt',
    'django_mptt_admin',
    'haystack',
    'pipeline',
    'paypal.standard.pdt',
    'paypal.standard.ipn',
    'pagination_bootstrap',
    'daterange_filter',
    'breadcrumbs',
    'captcha',
)

PROJECT_APPS = (
    'homepage',
    'cart',
    'shipping',
    'mypaypal',
    'order',
    'info',
)

INSTALLED_APPS = MODELTRANSLATION_APP + DJANGO_APPS + THIRD_PARTY_APPS + PROJECT_APPS
```
Is this happening only to me?

**Comment by manikos** [comment]
Forgot to mention that I use django-haystack version 2.4.1 and Python 2.7.6.
If you need any other information I would be glad to hand it over.

**Comment by acdha** [comment]
Django 1.9 support is being tracked in #1277

**Comment by manikos** [comment]
Thank you for your response. I thought support for Django 1.9 was entirely finished, that's why the new haystack version 4.2.1.
Anyway, should I close this thread and post the same on #1277 ?

**Comment by acdha** [comment]
Sorry about the delays but as of 10bcc7668ccaab499f8db516fd59de182aadbcb4 the tests are passing on Django 1.9.

**Comment by manikos** [comment]
OK. I will test it on my project once 10bcc76 tests are passed. Thank you very much for the info!

**Comment by manikos** [comment]
OK. Tested and its working smoothly. Version tested and worked is `django-haystack==2.5.dev0`.

**Comment by LegoStormtroopr** [comment]
Any hints on when this might go into a prod release?

**Comment by acdha** [comment]
If you have time to help with testing that would accelerate the process



On Mon, May 9, 2016 at 3:24 PM -0700, "Samuel Spencer" <notifications@github.com> wrote:












Any hints on when this might go into a prod release?

**Comment by LegoStormtroopr** [comment]
I'd be glad if I am able. How can I help?

**Comment by acdha** [comment]
If you have time, test the current master branch and let us know how it works. I've been very busy with work & family but am hoping to get a release candidate on PyPI soon
