### ISSUE TITLE
ImportError: cannot import name signals

### ISSUE THREAD

**Issue by soaprofessional** [django-haystack/django-haystack#1288]
I am using django 1.9 and django-haystack 2.0.0 .
When I am trying to add url(r'^search/',include('haystack.urls')), to my urls.py, it is giving below errors in test server. 

Unhandled exception in thread started by <function wrapper at 0x03449F70>
Traceback (most recent call last):
  File "D:\myprogs\python279\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "D:\myprogs\python279\lib\site-packages\django\core\management\commands\runserver.py", line 116, in inner_run
    self.check(display_num_errors=True)
  File "D:\myprogs\python279\lib\site-packages\django\core\management\base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "D:\myprogs\python279\lib\site-packages\django\core\checks\registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "D:\myprogs\python279\lib\site-packages\django\core\checks\urls.py", line 10, in check_url_config
    return check_resolver(resolver)
  File "D:\myprogs\python279\lib\site-packages\django\core\checks\urls.py", line 19, in check_resolver
    for pattern in resolver.url_patterns:
  File "D:\myprogs\python279\lib\site-packages\django\utils\functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\myprogs\python279\lib\site-packages\django\core\urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "D:\myprogs\python279\lib\site-packages\django\utils\functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\myprogs\python279\lib\site-packages\django\core\urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "D:\myprogs\python279\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "D:\myprogs\eclipse\pythonworkspace\django_test\django_test\urls.py", line 24, in <module>
    url(r'^search/',include('haystack.urls')),
  File "D:\myprogs\python279\lib\site-packages\django\conf\urls\__init__.py", line 52, in include
    urlconf_module = import_module(urlconf_module)
  File "D:\myprogs\python279\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "D:\myprogs\python279\lib\site-packages\haystack\__init__.py", line 5, in <module>
    from haystack import signals
ImportError: cannot import name signals

**Comment by sampeka** [comment]
Django 1.9 isn't supported yet, pull in progress here - feel free to contribute towards it: https://github.com/django-haystack/django-haystack/pull/1277

**Comment by acdha** [comment]
Sorry about the delays but as of 10bcc7668ccaab499f8db516fd59de182aadbcb4 the tests are passing on Django 1.9. Please let us know if you encounter any other problems.
