### ISSUE TITLE
Error when attempting to remove an object from index

### ISSUE THREAD

**Issue by Kelvin-Chu** [django-haystack/django-haystack#1323]
* [ x ] Tested with the latest Haystack release

## Expected behaviour
objects to be removed from index

## Actual behaviour
throws error:
```
  removing 2 stale records.
ERROR:root:Error updating dishes using default
Traceback (most recent call last):
  File "/etc/cravus/env/lib/python3.4/site-packages/haystack/management/commands/update_index.py", line 188, in handle_label
    self.update_backend(label, using)
  File "/etc/cravus/env/lib/python3.4/site-packages/haystack/management/commands/update_index.py", line 289, in update_backend
    backend.remove(rec_id, commit=self.commit)
  File "/etc/cravus/env/lib/python3.4/site-packages/haystack/backends/elasticsearch_backend.py", line 196, in remove
    doc_id = get_identifier(obj_or_string)
  File "/etc/cravus/env/lib/python3.4/site-packages/haystack/utils/__init__.py", line 37, in default_get_identifier
    return u"%s.%s" % (get_model_ct(obj_or_string), obj_or_string._get_pk_val())
  File "/etc/cravus/env/lib/python3.4/site-packages/haystack/utils/__init__.py", line 80, in get_model_ct
    return "%s.%s" % get_model_ct_tuple(model)
  File "/etc/cravus/env/lib/python3.4/site-packages/haystack/utils/__init__.py", line 74, in get_model_ct_tuple
    return (model._meta.app_label, model._meta.model_name)
AttributeError: 'int' object has no attribute '_meta'
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/etc/cravus/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/etc/cravus/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/etc/cravus/env/lib/python3.4/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/etc/cravus/env/lib/python3.4/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/etc/cravus/env/lib/python3.4/site-packages/haystack/management/commands/update_index.py", line 183, in handle
    return super(Command, self).handle(*items, **options)
  File "/etc/cravus/env/lib/python3.4/site-packages/django/core/management/base.py", line 548, in handle
    label_output = self.handle_label(label, **options)
  File "/etc/cravus/env/lib/python3.4/site-packages/haystack/management/commands/update_index.py", line 188, in handle_label
    self.update_backend(label, using)
  File "/etc/cravus/env/lib/python3.4/site-packages/haystack/management/commands/update_index.py", line 289, in update_backend
    backend.remove(rec_id, commit=self.commit)
  File "/etc/cravus/env/lib/python3.4/site-packages/haystack/backends/elasticsearch_backend.py", line 196, in remove
    doc_id = get_identifier(obj_or_string)
  File "/etc/cravus/env/lib/python3.4/site-packages/haystack/utils/__init__.py", line 37, in default_get_identifier
    return u"%s.%s" % (get_model_ct(obj_or_string), obj_or_string._get_pk_val())
  File "/etc/cravus/env/lib/python3.4/site-packages/haystack/utils/__init__.py", line 80, in get_model_ct
    return "%s.%s" % get_model_ct_tuple(model)
  File "/etc/cravus/env/lib/python3.4/site-packages/haystack/utils/__init__.py", line 74, in get_model_ct_tuple
    return (model._meta.app_label, model._meta.model_name)
AttributeError: 'int' object has no attribute '_meta'
```

## Steps to reproduce the behaviour

1. create object and index
2. remove object
3. run python manage.py update_index --remove

I changed doc_id = get_identifier(obj_or_string) to just doc_id = obj_or_string and it's working for me as expected... but i'm sure get_identifier is there for a reason.

## Configuration

* Operating system version: Centos 7
* Search engine version: 1.5.2
* Python version: 3.4.4
* Django version: 1.9.1
* Haystack version: 2.5.dev0

**Comment by zxwild** [comment]
I had the same issue which was raised by field like this:
```
class ItemIndex(indexes.SearchIndex, indexes.Indexable):
    # replace id by some_item_id and reindex
    id = indexes.CharField(model_attr='id', null=True)
```

this field conflicts with built-in id system, which should be like this: `app_name.item_name.123`
and replaces this id by plain number `123`

it can be investigated by `SearchIndex.prepare` method where this id is replaced by declared field.

a right id should be generated by this method
`from haystack.utils import get_identifier`

**Comment by esperyong** [comment]
i found two opiton:
1. set HAYSTACK_IDENTIFIER_METHOD
use a method just like:
```
def get_identifier(obj_or_string):
    return obj_or_string
```

2.remove the id field in the IndexItem Class,let update_index use the <app_label>.<object_name>.<pk> as identifier , it better than use plain pk,because model's pk can collision.

hope it helpful.
