### ISSUE TITLE
Update index via crontab with russian model name

### ISSUE THREAD

**Issue by MaximKalga** [django-haystack/django-haystack#1374]
Hi! I work with russian language. When I run update_index in shell it's OK, but when I run it via crontab, I have an error:

```
Traceback (most recent call last):
  File "/home/dl/venv/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 188, in handle_label
    self.update_backend(label, using)
  File "/home/dl/venv/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 222, in update_backend
    print(u"Indexing %d %s" % (total, force_text(model._meta.verbose_name_plural)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 14-19: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/dl/dl/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/dl/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/dl/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/dl/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/dl/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/dl/venv/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 183, in handle
    return super(Command, self).handle(*items, **options)
  File "/home/dl/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 548, in handle
    label_output = self.handle_label(label, **options)
  File "/home/dl/venv/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 188, in handle_label
    self.update_backend(label, using)
  File "/home/dl/venv/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 222, in update_backend
    print(u"Indexing %d %s" % (total, force_text(model._meta.verbose_name_plural)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 14-19: ordinal not in range(128)

```

For this case I handled exception and now it's working good:
...haystack/management/commands/update_index.py, line 222:

```
try:
    print(u"Indexing %d %s" % (total, force_text(model._meta.verbose_name_plural)))
except UnicodeEncodeError:
    print(u"Indexing %d %s" % (total, 'items'))

```

* Operating system version: ubuntu 14.04
* Search engine version: 1.7.2
* Python version: 2.7
* Django version: 1.9.6
* Haystack version: 2.4.1

**Comment by claudep** [comment]
I guess that when running via crontab, the LOCALE is not set (ie non-UTF-8). Try to set the locale for your cron script to a UTF-8 locale (see http://www.chrisneedham.com/posts/2014/06/21/ruby-cron-utf8.html for example).
