### ISSUE TITLE
MapperParsingException[Root mapping definition has unsupported parameters: [_boost : {name=boost, null_value=1.0}]]

### ISSUE THREAD

**Issue by quadrim** [django-haystack/django-haystack#1378]
* [YES ] Tested with the latest Haystack release
* [YES] Tested with the current Haystack master branch -- It started giving me error: 

> 
>   File "/home/moin/workspace/api/back-end/src/django-haystack/haystack/utils/loading.py", line 18, in <module>
>     from haystack.utils.app_loading import haystack_get_app_modules
>   File "/home/moin/workspace/api/back-end/src/django-haystack/haystack/utils/app_loading.py", line 4, in <module>
>     from django.apps import apps
> ImportError: No module named apps

as I am using Django version: _1.6.5_
===========================================================================

I am getting: 

> MapperParsingException[Root mapping definition has unsupported parameters:  [_boost : {name=boost, null_value=1.0}]]

 error in elasticsearch log while doing 

> SearchQuerySet().all()

 which returns empty list.

Complete stacktrace of the error is:

[2016-06-05 21:39:59,604][DEBUG][action.admin.indices.mapping.put] [MY.ELASTIC.SEARCH.IP] failed to put mappings on indices [[current_location]], type [modelresult]
MapperParsingException[Root mapping definition has unsupported parameters:  [_boost : {name=boost, null_value=1.0}]]
	at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:171)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:159)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:99)
	at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:508)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:257)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230)
	at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:468)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:772)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

## Configuration

* Operating system version: Ubunut 14.04
* Search engine version:
* Python version: 2.7
* Django version: 1.6.5
* Haystack version: 2.4.1

**Comment by ellisonleao** [comment]
Having this issue too. My log is

```
[2016-06-11 15:19:17,667][DEBUG][action.admin.indices.mapping.put] [Scimitar] failed to put mappings on indices [[esseproduto]], type [modelresult]
MapperParsingException[Root mapping definition has unsupported parameters:  [_boost : {null_value=1.0, name=boost}]]
	at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:171)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:159)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:99)
	at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:508)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:257)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230)
	at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:468)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:772)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```
Configuration
------------------

Operating system version: Ubuntu 14.04
Search engine version:
Python version: 3.5.1
Django version: 1.9.7
Haystack version: 2.4.1

**Comment by quadrim** [comment]
After some research, I figured out that this issues is because Haystack is not compatible with Elasticsearch 2.x . The "[_boost" parameter sent by haystack is no longer supported by Elasticsearch. So, as of now I am using normal HTTP request to query my elasticsearch cluster until and unless newer verison of haystack with issue fixed is released.
