### ISSUE TITLE
More like this not working

### ISSUE THREAD

**Issue by jTiKey** [django-haystack/django-haystack#1398]
* [x] Tested with the latest Haystack release
* [] Tested with the current Haystack master branch

## Expected behaviour
Should show 'More like this' for a current document.
## Actual behaviour

```
Traceback (most recent call last):
  File "/home/vagrant/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_exec.py", line 3, in Exec
    exec exp in global_vars, local_vars
  File "<input>", line 1, in <module>
  File "/home/vagrant/.pyenv/versions/2.7.6/envs/blook/lib/python2.7/site-packages/haystack/query.py", line 87, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE])
  File "/home/vagrant/.pyenv/versions/2.7.6/envs/blook/lib/python2.7/site-packages/haystack/query.py", line 272, in __getitem__
    self._fill_cache(start, bound)
  File "/home/vagrant/.pyenv/versions/2.7.6/envs/blook/lib/python2.7/site-packages/haystack/query.py", line 171, in _fill_cache
    results = self.query.get_results(**kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.6/envs/blook/lib/python2.7/site-packages/haystack/backends/__init__.py", line 640, in get_results
    self.run_mlt(**kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.6/envs/blook/lib/python2.7/site-packages/haystack/backends/elasticsearch_backend.py", line 945, in run_mlt
    results = self.backend.more_like_this(self._mlt_instance,
    additional_query_string, **search_kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.6/envs/blook/lib/python2.7/site-packages/haystack/backends/elasticsearch_backend.py", line 555, in more_like_this
    raw_results = self.conn.mlt(index=self.index_name, doc_type='modelresult', id=doc_id, mlt_fields=[field_name], **params)
AttributeError: 'Elasticsearch' object has no attribute 'mlt'
``` 
## Steps to reproduce the behaviour

1. Call the more_like_this method on a SearchQuerySet()

## Configuration

* Operating system version: Ubuntu 14.04.3 LTS
* Search engine version: Elasticsearch 2.3.3
* Python version: Python 2.7.6 
* Django version: Django 1.8.8
* Haystack version:  2.4.1

**Comment by jTiKey** [comment]
Seems like 2.5.0 fixed it.

**Comment by westurner** [comment]
* "The mlt method had been removed" https://github.com/elastic/elasticsearch-py/issues/310

**Comment by acdha** [comment]
@westurner Please open a new issue / pull-request for that

**Comment by kezabelle** [comment]
As far as I can tell, mlt as a method was removed in [fa62ae71bf068f9d1e97a415a6fe0fc4c32669b1](https://github.com/elastic/elasticsearch-py/commit/fa62ae71bf068f9d1e97a415a6fe0fc4c32669b1) and has never existed in the 2.x series?

**Comment by acdha** [comment]
That'd make it easier since we already decided to break es2 support into a separate backend (see #1391) so we could just change the `mlt` implementation in that one and leave the ES  1.x code unmodified.
