### ISSUE TITLE
"update_index" with workers not working, elasticsearch

### ISSUE THREAD

**Issue by richardasaurus** [django-haystack/django-haystack#1422]
This only happens when `--workers=4` is specified. Which I need as the index i'm updating is large.

Am I doing something wrong or is this a real isse?

* [x] Tested with the latest Haystack release
* [x] Tested with the current Haystack master branch

## Expected behaviour

The index should be updated

## Actual behaviour

```bash
my_app_name)vagrant@vagrant-ubuntu-trusty:/opt/dev/my_app_name$ ./manage.py update_index --remove --verbosity=2 --workers=4
System check identified some issues:

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_CONTEXT_PROCESSORS, TEMPLATE_DEBUG.
Skipping '<class 'django.contrib.contenttypes.models.ContentType'>' - no index.
Skipping '<class 'django.contrib.admin.models.LogEntry'>' - no index.
Skipping '<class 'django.contrib.auth.models.Permission'>' - no index.
Skipping '<class 'django.contrib.auth.models.Group'>' - no index.
Skipping '<class 'django.contrib.auth.models.User'>' - no index.
Skipping '<class 'django.contrib.sessions.models.Session'>' - no index.
Skipping '<class 'django.contrib.sites.models.Site'>' - no index.
Skipping '<class 'activity.models.Action'>' - no index.
Skipping '<class 'apps.titles.models.Genre'>' - no index.
Indexing 4833363 peoples
[INFO/PoolWorker-1] child process calling self.run()
[INFO/PoolWorker-2] child process calling self.run()
[INFO/PoolWorker-3] child process calling self.run()
[INFO/PoolWorker-4] child process calling self.run()
[ERROR/MainProcess] Error updating titles using default
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/my_app_name/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 214, in handle
    self.update_backend(label, using)
  File "/home/vagrant/.virtualenvs/my_app_name/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 265, in update_backend
    successful_tasks = pool.map(update_worker, ghetto_queue)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
AttributeError: 'ConnectionHandler' object has no attribute 'thread_local'
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/.virtualenvs/my_app_name/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/.virtualenvs/my_app_name/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/.virtualenvs/my_app_name/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vagrant/.virtualenvs/my_app_name/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/.virtualenvs/my_app_name/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 214, in handle
    self.update_backend(label, using)
  File "/home/vagrant/.virtualenvs/my_app_name/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 265, in update_backend
    successful_tasks = pool.map(update_worker, ghetto_queue)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
AttributeError: 'ConnectionHandler' object has no attribute 'thread_local'
[INFO/MainProcess] process shutting down
[INFO/PoolWorker-3] process shutting down
[INFO/PoolWorker-4] process shutting down
[INFO/PoolWorker-3] process exiting with exitcode 0
[INFO/PoolWorker-4] process exiting with exitcode 0
[INFO/PoolWorker-2] process shutting down
[INFO/PoolWorker-2] process exiting with exitcode 0
[INFO/PoolWorker-1] process shutting down
[INFO/PoolWorker-1] process exiting with exitcode 0
```

## Steps to reproduce the behaviour

1. Run `./manage.py update_index --remove --verbosity=2 --workers=4`

## Configuration

**Note, I've tried this on multiple machines with the same result**

* Operating system version: Ubuntu 14.04 LTS
* Search engine version: elasticsearch 1.7.2
* Python version: 2.7.9
* Django version: 1.9.9
* Haystack version: 2.5.0

**Comment by richardasaurus** [comment]
@acdha This commit https://github.com/richardasaurus/django-haystack/commit/b8b8f984f97588f05e11ce9bce15d31d1b16226e

Gets rid of the error, and lets things index, but it there some harm doing that could cause?

---

Changing from multiprocessing Pool to use gevent also fixes this in my case strangely. Note it's trying to index 40mil records
