### ISSUE TITLE
OperationalError: SSL SYSCALL error: EOF detected

### ISSUE THREAD

**Issue by acer9997** [django-haystack/django-haystack#1423]
Trying to rebuild an index for about 240,000 records by issuing the rebuild_index command. The rebuilding gets through about 14,000 records and then an error is thrown. 

The environment is Heroku and using Searchly's Elastic Search. The same error occurs whether this is running on a local development machine, or the command is sent directly to the Heroku dyno.

Here is the full stack trace of the error:

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/acer9997/django-venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/acer9997/django-venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/acer9997/django-venv/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/acer9997/django-venv/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/acer9997/django-venv/src/django-haystack/haystack/management/commands/rebuild_index.py", line 26, in handle
    call_command('update_index', **options)
  File "/Users/acer9997/django-venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 119, in call_command
    return command.execute(*args, **defaults)
  File "/Users/acer9997/django-venv/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/acer9997/django-venv/src/django-haystack/haystack/management/commands/update_index.py", line 183, in handle
    return super(Command, self).handle(*items, **options)
  File "/Users/acer9997/django-venv/lib/python2.7/site-packages/django/core/management/base.py", line 548, in handle
    label_output = self.handle_label(label, **options)
  File "/Users/acer9997/django-venv/src/django-haystack/haystack/management/commands/update_index.py", line 188, in handle_label
    self.update_backend(label, using)
  File "/Users/acer9997/django-venv/src/django-haystack/haystack/management/commands/update_index.py", line 233, in update_backend
    do_update(backend, index, qs, start, end, total, verbosity=self.verbosity, commit=self.commit)
  File "/Users/acer9997/django-venv/src/django-haystack/haystack/management/commands/update_index.py", line 96, in do_update
    backend.update(index, current_qs, commit=commit)
  File "/Users/acer9997/django-venv/src/django-haystack/haystack/backends/elasticsearch_backend.py", line 169, in update
    for obj in iterable:
  File "/Users/acer9997/django-venv/lib/python2.7/site-packages/django/db/models/query.py", line 258, in __iter__
    self._fetch_all()
  File "/Users/acer9997/django-venv/lib/python2.7/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/acer9997/django-venv/lib/python2.7/site-packages/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/Users/acer9997/django-venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "/Users/acer9997/django-venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/acer9997/django-venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/acer9997/django-venv/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/acer9997/django-venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.OperationalError: SSL SYSCALL error: EOF detected
```

Here is how HAYSTACK_CONNECTIONS is configured in Django's settings.py:
```
# Elastic search configuration / Get your connection url from Searchly dashboard
es = urlparse(environ.get('SEARCHBOX_URL'))
port = es.port or 80
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.elasticsearch_backend.ElasticsearchSearchEngine',
        'URL': es.scheme + '://' + es.hostname + ':' + str(port),
        'INDEX_NAME': 'documents',
        'TIMEOUT': 60 * 5,
    },
}
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'
if es.username:
    HAYSTACK_CONNECTIONS['default']['KWARGS'] = {"http_auth": es.username + ':' + es.password}
```

**Comment by acer9997** [comment]
Lowered the BATCH_SIZE to 100 and so far 45,000 records have been indexed ... but whew, it's slow.

**Comment by acdha** [comment]
The underlying problem here is ElasticSearch, probably due to the heavy load causing a timeout. haystack 2.5 added retries to indexing, which should help with this.

If you're seeing performance issues, standard Django template performance techniques work well – most commonly, it's because rendering the template triggers an unexpected number of database queries and changing your index's `index_queryset` to use things like `select_related` or `prefetch_related` will generate significant performance improvements without too much work.

**Comment by SteveByerly** [comment]
@acer9997 If there's further information, please feel free to re-open this issue.
