### ISSUE TITLE
Unable to order_by score

### ISSUE THREAD

**Issue by jwnorman** [django-haystack/django-haystack#1431]
I am able to sort my `SearchQuerySet` by my personally-defined field, `modified`, but not Haystack's build-in `score`. When I only order by `modified`, each SearchResult does, in fact, have a score. I couldn't find anything about this in Haystack's documentation, but I did found an example online that seemed to indicate that the `.order_by('-score', '-modified')` below should work:

```python
        sqs = (SearchQuerySet()
               .models(MyModel)
               .order_by('-score', '-modified'))
```

but it doesn't; instead, I get a GET 500 error.

* [ ] Tested with the latest Haystack release
* [ ] Tested with the current Haystack master branch

I am unable to test with the latest Haystack release nor the current master branch.

## Expected behaviour
The SearchResults are sorted in descending order, first by `score` and then by `modified`.

## Actual behaviour
The search gets cut short and I receive `"GET /api/v3/itemsearch/search/?page=1&q=ap%5B%5D=YLUKFXJR&_=1472851995790 HTTP/1.1" 500 3072` as well as `- Broken pipe from ('127.0.0.1', 61071)`.

## Steps to reproduce the behaviour

1. Create a field in `search_indexes.py` that you can order by.
2. Order by this field and verify that it works.
3. Verify that each SearchResult indeed has a score.
4. Add `score` to the `order_by()` function.

## Configuration

* Operating system version: OS X El Capitan Version 10.11.6
* Search engine version: Whoosh 2.6.0
* Python version: 2.7.8
* Django version: 1.8.6
* Haystack version: 2.4.1

**Comment by SteveByerly** [comment]
Can you post the example that made it seem like it would work?

From my experience, you cannot sort on the score as it's not a field in the document like your `modified` field. You can do custom stuff depending on your backend, but I think that goes beyond what haystack lets you do.

What I think you really might want to do is Boost:
https://django-haystack.readthedocs.io/en/v2.5.0/boost.html

Alternatively, if you have small result sets, you could sort them in Python:
return sorted(results, key=lambda x: (x.score, x.modified)])

**Comment by jwnorman** [comment]
I believe the example I found was in [this SO post](http://stackoverflow.com/a/3105715/3131893).

Thanks for your two suggestions. I'm not sure if I'll be able to use Field Boost because, from the documentation, "field boosting only has an effect when the SearchQuerySet filters on the field which has been boosted," and I don't filter on `modified`.

As for sorting the results in Python, I will try this. For some reason, I feel like I've tried this and run into an issue, but will try again. Thanks again 👍

**Comment by SteveByerly** [comment]
I just tried sorting by score in my own code, and proved myself wrong. You can indeed sort by score - at least using solr :)

When doing `.order_by('score')`:
Haystack tells the engine to return fields: `* score`, meaning it will return all fields for the documents and the score.
```
...fl=*+score&sort=score+asc...
```

I'm wondering if there's an issue with the whoosh backend. Are you able to see/log the queries being sent to your whoosh process from haystack? Are you able to query whoosh directly to see if it's able to sort the way solr is?

I'll keep digging in the meantime, but it'll only be when i have a bit more time.

**Comment by jobelenus** [comment]
Sorting in python is pretty quick, you can always read your results to a multi-dimensional dict with keys of score and your custom field, and then just write a sort function.

**Comment by rzelayafavila** [comment]
Sorting by score with the Elasticsearch backend is also not possible (using Python 2.7.12 and the latest version of Haystack, 2.5.1). Looking at the Traceback, it does seem like the issue stems from the backend implementations:

```
Traceback (most recent call last):
  File "/home/.../venv/local/lib/python2.7/site-packages/haystack/backends/elasticsearch_backend.py", line 524, in search
    _source=True)
  File "/home/.../venv/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/.../venv/local/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 531, in search
    doc_type, '_search'), params=params, body=body)
  File "/home/.../venv/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/.../venv/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 93, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/.../venv/local/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
```
What happens in the solr backend implementation that does not happen in the whoosh or elasticsearch backend implementations?

**Comment by acdha** [comment]
This is basically an area where we need to paper over the underlying implementation differences. The score is a calculated field rather than one which actually exists on the index: in Solr, that's exposed as `score`, in ElasticSearch it's `_score`, and Whoosh has an actual Python class which you can instantiate and add to the list of sort fields.

I'm hesitant to say Haystack should try to magically handle this based on the field name since it's possible that someone has a `score` field defined on their model which is not the calculated score field from the backend and am thinking we should make a constant so `order_by(Haystack.SORT_SCORE_ASC, …)` and that could be expanded with the correct value for the active backend.

**Comment by cgreene** [comment]
@acdha: Just poking my head in here - what about putting a note in the documentation on this? It wouldn't require magically handling it but could save people time. It does seem a fair number of people are ending up here.

**Comment by acdha** [comment]
@cgreene Agreed – there's clearly a need.

**Comment by rzelayafavila** [comment]
@acdha Ok, I can confirm that sorting by using ``_score`` in the ``order_by()`` function works with the Elasticsearch backend. Thus, my sorting code looks something like this:
```
sqs = SearchQuerySet().models(MyModel).order_by('-_score', 'field2')
```

**Comment by JIElite** [comment]
@rzelayafavila  Thank you!  help me a lot!

**Comment by sbywater** [comment]
2022 and this is still an issue. If haystack does not want to add a setting for this, I can submit a documentation pull request.
