### ISSUE TITLE
Error facet in es2

### ISSUE THREAD

**Issue by Zverushko** [django-haystack/django-haystack#1443]
* [yes] Tested with the latest Haystack release
* [yes] Tested with the current Haystack master branch

## Actual behaviour
`PUT /haystack/_mapping/modelresult [status:400 request:0.014s]
GET /haystack/modelresult/_search?_source=true [status:400 request:0.007s]
Failed to query Elasticsearch using '*:*': TransportError(400, 'search_phase_execution_exception', 'failed to parse search source. unknown search element [facets]')
Traceback (most recent call last):
  File "/home/zverushko/.python35/lib/python3.5/site-packages/haystack/backends/elasticsearch_backend.py", line 524, in search
    _source=True)
  File "/home/zverushko/.python35/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/zverushko/.python35/lib/python3.5/site-packages/elasticsearch/client/__init__.py", line 539, in search
    doc_type, '_search'), params=params, body=body)
  File "/home/zverushko/.python35/lib/python3.5/site-packages/elasticsearch/transport.py", line 327, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/zverushko/.python35/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/zverushko/.python35/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 113, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'search_phase_execution_exception', 'failed to parse search source. unknown search element [facets]')`

## Steps to reproduce the behaviour

`from haystack.query import SearchQuerySet

all_results = SearchQuerySet().all().facet('attrs')`

## Configuration

* Operating system version: Ubuntu 16.04
* Search engine version: ES2 latest from off rep
* Python version: 3.5
* Django version: 1.10
* Haystack version: 2.5

**Comment by acdha** [comment]
ElasticSearch 2 is not yet officially supported - see https://github.com/django-haystack/django-haystack/pull/1391 for a branch which could use some additional help & testing

**Comment by acdha** [comment]
I just uploaded v2.6.0 to PyPI which has ES2 support
