### ISSUE TITLE
Incorrect autocomplete queries generated with HAYSTACK_DEFAULT_OPERATOR = 'OR'

### ISSUE THREAD

**Issue by dchanm** [django-haystack/django-haystack#1471]
* [x] Tested with the latest Haystack release
* [ ] Tested with the current Haystack master branch

## Expected behaviour
Query results returned

## Actual behaviour
TransportError and empty results
```
2017-01-09T05:33:14.469714+00:00 app[worker.1]: Failed to query Elasticsearch using '( OR (tags_auto:(foo) AND tags_auto:(bar)))': TransportError(400, 'search_phase_execution_exception', 'parse_exception: Encountered " <OR> "OR "" at line 1, column 2.\nWas expecting one of:\n    <NOT> ...\n    "+" ...\n    "-" ...\n    <BAREOPER> ...\n    "(" ...\n    "*" ...\n    <QUOTED> ...\n    <TERM> ...\n    <PREFIXTERM> ...\n    <WILDTERM> ...\n    <REGEXPTERM> ...\n    "[" ...\n    "{" ...\n    <NUMBER> ...\n    <TERM> ...\n    "*" ...\n    ')
2017-01-09T05:33:14.469716+00:00 app[worker.1]: Traceback (most recent call last):
2017-01-09T05:33:14.469717+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/haystack/backends/elasticsearch_backend.py", line 524, in search
2017-01-09T05:33:14.469719+00:00 app[worker.1]:     _source=True)
2017-01-09T05:33:14.469719+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 71, in _wrapped
2017-01-09T05:33:14.469720+00:00 app[worker.1]:     return func(*args, params=params, **kwargs)
2017-01-09T05:33:14.469721+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/elasticsearch/client/__init__.py", line 569, in search
2017-01-09T05:33:14.469722+00:00 app[worker.1]:     doc_type, '_search'), params=params, body=body)
2017-01-09T05:33:14.469722+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/elasticsearch/transport.py", line 327, in perform_request
2017-01-09T05:33:14.469723+00:00 app[worker.1]:     status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
2017-01-09T05:33:14.469724+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 124, in perform_request
2017-01-09T05:33:14.469725+00:00 app[worker.1]:     self._raise_error(response.status, raw_data)
2017-01-09T05:33:14.469725+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 122, in _raise_error
2017-01-09T05:33:14.469726+00:00 app[worker.1]:     raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
2017-01-09T05:33:14.469730+00:00 app[worker.1]: elasticsearch.exceptions.RequestError: TransportError(400, 'search_phase_execution_exception', 'parse_exception: Encountered " <OR> "OR "" at line 1, column 2.\nWas expecting one of:\n    <NOT> ...\n    "+" ...\n    "-" ...\n    <BAREOPER> ...\n    "(" ...\n    "*" ...\n    <QUOTED> ...\n    <TERM> ...\n    <PREFIXTERM> ...\n    <WILDTERM> ...\n    <REGEXPTERM> ...\n    "[" ...\n    "{" ...\n    <NUMBER> ...\n    <TERM> ...\n    "*" ...\n    ')
```
## Steps to reproduce the behaviour

1. Set `HAYSTACK_DEFAULT_OPERATOR = 'OR'` in settings.py
2.  
```python
from haystack.query import SearchQuerySet
SearchQuerySet().autocomplete(content_auto='foo')[0]
```

## Configuration

* Operating system version: Ubuntu 14.04.5
* Search engine version: elasticsearch 2.4.0
* Python version: 3.5.2
* Django version: 1.10.3
* Haystack version: 2.6.0

The issue disappears if I change `HAYSTACK_DEFAULT_OPERATOR = 'AND'`. The bug appears to be an interaction between `filter_or` and `SQ` objets
```python
# SQ objects
>>> SearchQuerySet().filter_or(SQ(content='foo')).query.__str__()
'( OR (foo))'
>>> SearchQuerySet().filter_and(SQ(content='foo')).query.__str__()
'(foo)'
# no SQ objects
>>> SearchQuerySet().filter_and(content='foo').query.__str__()
'(foo)'
>>> SearchQuerySet().filter_or(content='foo').query.__str__()
'(foo)'
```

**Comment by hubert10** [comment]
Met the same problem when changiing `HAYSTACK_DEFAULT_OPERATOR = 'AND'` into `HAYSTACK_DEFAULT_OPERATOR = 'OR'` to be able to filter search results with OR parameter. 
In addition to that for my case it returns empty results and in my elasticsearch server I found the following warning: `elasticsearch.exceptions.RequestError: TransportError(400, 'search_phase_execution_exception', 'Failed to parse query [( OR text:(*eric*) OR text:(*eric*) OR text:(*eric*))]')
[02/Jun/2017 11:25:07] "GET /en/search/aggs/?keywords__contains=eric HTTP/1.1" 200 5773
`
Any help or suggestion would be helpful!

**Comment by keshavgoel21** [comment]
The difference in ElasticSearch query formed while using defsult value of HAYSTACK_DEFAULT_OPERATOR ie. ‘AND’ and while using HAYSTACK_DEFAULT_OPERATOR = u'OR' is shown below.

In case of HAYSTACK_DEFAULT_OPERATOR = u'AND'
```
{
	"query": {
		"filtered": {
			"filter": {
				"terms": {
					"django_ct": [
						"students.student"
					]
				}
			},
			"query": {
				"query_string": {
					"fuzzy_max_expansions": 50,
					"auto_generate_phrase_queries": "True",
					"default_operator": "AND",
					"analyze_wildcard": "True",
					"query": "content_auto:(foo)",
					"default_field": "text",
					"fuzzy_min_sim": 0.5
				}
			}
		}
	},
	"size": 1,
	"from": 0,
	"suggest": {
		"suggest": {
			"text": "content_auto:(foo)",
			"term": {
				"field": "_all"
			}
		}
	}
}
```

In case of HAYSTACK_DEFAULT_OPERATOR = u'OR'

```
{
	"query": {
		"filtered": {
			"filter": {
				"terms": {
					"django_ct": [
						"students.student"
					]
				}
			},
			"query": {
				"query_string": {
					"fuzzy_max_expansions": 50,
					"auto_generate_phrase_queries": "True",
					"default_operator": "OR",
					"analyze_wildcard": "True",
					"query": "( OR content_auto:(foo))",
					"default_field": "text",
					"fuzzy_min_sim": 0.5
				}
			}
		}
	},
	"size": 1,
	"from": 0,
	"suggest": {
		"suggest": {
			"text": "( OR content_auto:(foo))",
			"term": {
				"field": "_all"
			}
		}
	}
}
```

As you could see the `query` in `query_string` in case of 'OR' there is erroneous query that involves 'OR' prepended  without any second operand despite of having   `default_operator` parameter in query_string. I will fix it and give the Merge Request soon.
