### ISSUE TITLE
Faceting does not work with 2.6.0

### ISSUE THREAD

**Issue by mdf-github** [django-haystack/django-haystack#1477]
* [X] Tested with the latest Haystack release (2.6.0)
* [ ] Tested with the current Haystack master branch

## Expected behaviour
Obtained using package [elasticsearch2-haystack](https://pypi.python.org/pypi/elasticsearch2-haystack)
```
>>> from haystack.query import SearchQuerySet as SQS
>>> from models import *
>>> s = SQS().facet('author')
>>> s.facet_counts()
{'fields': {'author': [('mike-5', 4), ('irene-2', 3), ('jeff-1', 2)]}, 'queries': {}, 'dates': {}}
>>>
```

## Actual behaviour
```
GET /haystack/modelresult/_search?_source=true [status:400 request:0.031s]
Failed to query Elasticsearch using '*:*': TransportError(400, 'search_phase_execution_exception', 'failed to parse search source. unknown search element [facets]')
Traceback (most recent call last):
  File "E:\Documents\irene\noteproj\virtual\lib\site-packages\haystack\backends\elasticsearch_backend.py", line 524, in search
    _source=True)
  File "E:\Documents\irene\noteproj\virtual\lib\site-packages\elasticsearch\client\utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "E:\Documents\irene\noteproj\virtual\lib\site-packages\elasticsearch\client\__init__.py", line 539, in search
    doc_type, '_search'), params=params, body=body)
  File "E:\Documents\irene\noteproj\virtual\lib\site-packages\elasticsearch\transport.py", line 327, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "E:\Documents\irene\noteproj\virtual\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 110, in perform_request
    self._raise_error(response.status, raw_data)
  File "E:\Documents\irene\noteproj\virtual\lib\site-packages\elasticsearch\connection\base.py", line 114, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'search_phase_execution_exception', 'failed to parse search source. unknown search element [facets]')
{}
```

## Steps to reproduce the behaviour

1. Download and run elasticsearch 2.4.3.
2. Add the following in models.py

```
class Note(models.Model):
        user = models.ForeignKey(User, related_name='note')
```

3. Add the following in search_indexes.py:
```
class NoteIndex(indexes.SearchIndex, indexes.Indexable):
	text = indexes.EdgeNgramField(document=True, use_template=True)
	name = indexes.CharField(model_attr='name')
	author = indexes.CharField(model_attr='user', faceted=True)

	def get_model(self):
		return Note

	def index_queryset(self, using=None):
		return self.get_model().objects.all()
```
4. And in settings.py
```
	 'default': {
	 	'ENGINE': 'haystack.backends.elasticsearch_backend.ElasticsearchSearchEngine',
	 	'URL': 'http://127.0.0.1:9200/',
	 	'INDEX_NAME': 'haystack',
	 },
```

## Configuration

* Operating system version: Windows 10
* Search engine version: Elasticsearch 2.4.3 with elasticsearch-py 2.4.1
* Python version: 3.5.2
* Django version: 1.10.1
* Haystack version: 2.6.0

**Comment by acdha** [comment]
ElasticSearch2-haystack is a separate package. Can you test with the stock haystack?

**Comment by mdf-github** [comment]
Yes I have tested this on stock haystack. Faceting works on elasticsearch2-haystack, but not on the stock version.

**Comment by barseghyanartur** [comment]
@mdf-github:

You're using wrong backend for elasticsearch 2.x. You should be using `elasticsearch2_backend` instead.

```python

HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.elasticsearch2_backend.Elasticsearch2SearchEngine',
        'URL': 'http://127.0.0.1:9200/',
        'INDEX_NAME': 'haystack',
    },
}
```

**Comment by mdf-github** [comment]
@barseghyanartur That solved the problem, thanks a lot!!! It would also be great if this can be written in the v2.6.0 docs since only the old backend is included there.

**Comment by chirag7jain** [comment]
I am still facing the issue. I tried with above changes. Have the same environment config as above

#1485

**Comment by chirag7jain** [comment]
@acdha can you please help out with this

**Comment by acdha** [comment]
@chirag7jain If you have a complete reproducible testcase which fails against the current versions, that might be worth a separate ticket since switching the backends appears to have solved the original requester's problem.

**Comment by rhblind** [comment]
@chirag7jain Hey, just want to chip in that the elasticsearch2 backend might not be supported by drf-haystack just yet, so the issue might lay there.
Currently trying to find some time to update the library..
