### ISSUE TITLE
./manage.py build_solr_schema fails

### ISSUE THREAD

**Issue by PaulHughes99** [django-haystack/django-haystack#1536]
* [* ] Tested with the latest Haystack release
* [ ] Tested with the current Haystack master branch

## Expected behaviour
Build an SOLR schema.xml

## Actual behaviour
**Error: TypeError: context must be a dict rather than Context.
(appears to be using a deprecated method)**

## Steps to reproduce the behaviour

1. New install
2. Build the default set-up
3. Run  ./manage.py build_solr_schema

```
:~/newhay/myproject$ ./manage.py build_solr_schema

Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/newhay/newhay/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/newhay/newhay/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/newhay/newhay/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/newhay/newhay/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/newhay/newhay/local/lib/python2.7/site-packages/haystack/management/commands/build_solr_schema.py", line 30, in handle
    schema_xml = self.build_template(using=using)
  File "/home/ubuntu/newhay/newhay/local/lib/python2.7/site-packages/haystack/management/commands/build_solr_schema.py", line 59, in build_template
    return render_to_string(t,c) #t.render(c)
  File "/home/ubuntu/newhay/newhay/local/lib/python2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/home/ubuntu/newhay/newhay/local/lib/python2.7/site-packages/django/template/backends/django.py", line 64, in render
    context = make_context(context, request, autoescape=self.backend.engine.autoescape)
  File "/home/ubuntu/newhay/newhay/local/lib/python2.7/site-packages/django/template/context.py", line 287, in make_context
    ****raise TypeError('context must be a dict rather than %s.' % context.__class__.__name__)
TypeError: context must be a dict rather than Context.****
```

## Configuration
* Operating system version:  Ubuntu
* Search engine version: Solr 6.6.0
* Python version: 2.7.12
* Django version: 1.11.3
* Haystack version: 2.6.1

**Comment by acdha** [comment]
Haystack 2.6.1 doesn't support Django 1.11. You can use the master branch right now or an earlier version of Django until the next release.
