### ISSUE TITLE
Attribute Error: 'NoneType' object has no attribute 'clone' when installing with pip

### ISSUE THREAD

**Issue by ursomniac** [django-haystack/django-haystack#1573]
* [X] Tested with the latest Haystack release
* [X] Tested with the current Haystack master branch

## Expected behaviour

The software should install with pip.

## Actual behaviour

The software doesn't install with pip.

## Steps to reproduce the behaviour

1.

## Configuration

* Operating system version:

CentOS 7.4

* Search engine version:
* Python version:

2.7

* Django version:

1.8.13

* Haystack version:

2.6.1

Diagnostics follow:

Collecting django-haystack
  Using cached django-haystack-2.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    Couldn't find index page for 'setuptools_scm' (maybe misspelled?)
    No local packages or download links found for setuptools-scm
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/jc/f_ds5mbs2xvbycw6rkjkt18r5js9q4/T/pip-build-xMRXL9/django-haystack/setup.py", line 68, in <module>
        setup_requires=['setuptools_scm'],
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "build/bdist.linux-i686/egg/setuptools/dist.py", line 260, in __init__
      File "build/bdist.linux-i686/egg/setuptools/dist.py", line 284, in fetch_build_eggs
      File "build/bdist.linux-i686/egg/pkg_resources.py", line 563, in resolve
      File "build/bdist.linux-i686/egg/pkg_resources.py", line 799, in best_match
      File "build/bdist.linux-i686/egg/pkg_resources.py", line 811, in obtain
      File "build/bdist.linux-i686/egg/setuptools/dist.py", line 327, in fetch_build_egg
      File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 434, in easy_install
      File "build/bdist.linux-i686/egg/setuptools/package_index.py", line 475, in fetch_distribution
    AttributeError: 'NoneType' object has no attribute 'clone'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/jc/f_ds5mbs2xvbycw6rkjkt18r5js9q4/T/pip-build-xMRXL9/django-haystack/

Please advise.

**Comment by GowthamG11** [comment]
Did u try with virtualenv?

I tried in my local pc it is installing

Regards,
Gowthaman G
