### ISSUE TITLE
Django 2.0 rebuild_index Error

### ISSUE THREAD

**Issue by rohan-krishna** [django-haystack/django-haystack#1589]
## Expected behaviour
Get some totals of how many models were processed and placed in the index.
## Actual behaviour
```
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\css111100\venvs\notes\lib\site-packages\django\core\management\__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "C:\Users\css111100\venvs\notes\lib\site-packages\django\core\management\__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\css111100\venvs\notes\lib\site-packages\django\core\management\base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\css111100\venvs\notes\lib\site-packages\django\core\management\base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "C:\Users\css111100\venvs\notes\lib\site-packages\haystack\management\commands\rebuild_index.py", line 36, in handle
    call_command('clear_index', **options)
  File "C:\Users\css111100\venvs\notes\lib\site-packages\django\core\management\__init__.py", line 133, in call_command
    ', '.join(sorted(valid_options)),
TypeError: Unknown option(s) for clear_index command: batchsize, workers. Valid options are: commit, help, interactive, no_color, nocommit, noinput, pythonpath, settings, skip_checks, stderr, stdout, traceback, using, verbosity, version.
```
## Configuration

* Operating system version: Windows 10
* Search engine version: Whoosh , Solr
* Python version: 3.4
* Django version: 2.0
* Haystack version: master

**Comment by acdha** [comment]
Django 2 is not supported yet: see https://github.com/django-haystack/django-haystack/pull/1582

**Comment by robertofd1995** [comment]
I have the same error right now

Operating system version: Windows 10
Search engine version: ElasticSeach 2.4.1
Python version: 3.6
Django version: 2.0
Haystack version: 2.7.0

**Comment by acdha** [comment]
I just merged #1582 and tagged v2.8.0: https://pypi.python.org/pypi/django-haystack/2.8.0

**Comment by edmenendez** [comment]
I'm having the same exact error. Version info below.

Django==2.0.13
django-haystack==2.8.1
Python=3.6.6
Whoosh==2.7.4  # also happens with SimpleEngine

**Comment by edmenendez** [comment]
Discovered there's a management command name conflict with another package. A namespace might solve it. Opened this ticket https://github.com/ellmetha/django-machina/issues/159 with the other package and leaving this comment here in case anyone else runs into it.
