### ISSUE TITLE
Django 2.0 rebuild_index Error

### ISSUE THREAD

**Issue by robertofd1995** [django-haystack/django-haystack#1593]
* [X] Tested with the latest Haystack release
* [ ] Tested with the current Haystack master branch

## Expected behaviour

Hello guys , i am trying to rebuild the index for first time , i am following the example of the tutorial
and i am getting the following when i try to run 

python manage.py rebuild_index

## Actual behaviour

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\rober\PycharmProjects\testSearch\venv\lib\site-packages\django\core\management\__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "C:\Users\rober\PycharmProjects\testSearch\venv\lib\site-packages\django\core\management\__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\rober\PycharmProjects\testSearch\venv\lib\site-packages\django\core\management\base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\rober\PycharmProjects\testSearch\venv\lib\site-packages\django\core\management\base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "C:\Users\rober\PycharmProjects\testSearch\venv\lib\site-packages\haystack\management\commands\rebuild_index.py", line 36, in handle
    call_command('clear_index', **options)
  File "C:\Users\rober\PycharmProjects\testSearch\venv\lib\site-packages\django\core\management\__init__.py", line 133, in call_command
    ', '.join(sorted(valid_options)),
TypeError: Unknown option(s) for clear_index command: batchsize, workers. Valid options are: commit, help, interactive, no_color, nocommit, noinput, pythonpath, settings, skip_checks, stderr, stdout, t
raceback, using, verbosity, version.

## Steps to reproduce the behaviour

1. Following the tutorial

## Configuration

Operating system version: Windows 10
Search engine version: ElasticSeach 2.4.1
Python version: 3.6
Django version: 2.0
Haystack version: 2.7.0

**Comment by robertofd1995** [comment]
I just try now to use , update index instead of rebuild_index and with this it works

**Comment by acdha** [comment]
Django 2.0 will be supported when #1582 is merged, which should be shortly. Please re-open if this is still an issue for you.

**Comment by acdha** [comment]
I just merged #1582 and tagged v2.8.0: https://pypi.python.org/pypi/django-haystack/2.8.0
