### ISSUE TITLE
"psycopg2.InterfaceError: cursor already closed" when updating the index

### ISSUE THREAD

**Issue by faxioman** [django-haystack/django-haystack#1606]
I'm using the whoosh backend and when I update the index using:

```
python manage.py update_index -k 1
```
all works fine.
But if I add the "-r" parameter in this way:

```
python manage.py update_index -k 1 -r
```

I get the exception: psycopg2.InterfaceError: cursor already closed

This is the stacktrace:

```
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.InterfaceError: cursor already closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/haystack/management/commands/update_index.py", line 230, in handle
    self.update_backend(label, using)
  File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/haystack/management/commands/update_index.py", line 303, in update_backend
    database_pks = set(smart_bytes(pk) for pk in qs.values_list('pk', flat=True))
  File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/modeltranslation/manager.py", line 484, in __iter__
    for row in super(FallbackFlatValuesListIterable, self).__iter__():
  File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/modeltranslation/manager.py", line 479, in __iter__
    for row in super(FallbackValuesListIterable, self).__iter__():
  File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/modeltranslation/manager.py", line 467, in __iter__
    for row in super(FallbackValuesIterable, self).__iter__():
  File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/django/db/models/query.py", line 106, in __iter__
    for row in compiler.results_iter(chunked_fetch=self.chunked_fetch):
  File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 841, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch)
  File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
  File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 889, in execute_sql
    cursor.execute(sql, params)
  File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/raven/contrib/django/client.py", line 123, in execute
    return real_execute(self, sql, params)
  File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.InterfaceError: cursor already closed
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.InterfaceError: cursor already closed
```

**Comment by faxioman** [comment]
This works:
```
python manage.py update_index -k 0 -r
```
