### ISSUE TITLE
Building index fails if two SearchIndex have the same field name and different type

### ISSUE THREAD

**Issue by manelclos** [django-haystack/django-haystack#1648]
* [x] Tested with the latest Haystack release
* [ ] Tested with the current Haystack master branch

## Expected behaviour
Indexing should not fail

## Actual behaviour
Indexing fails because field is being indexed with wrong type (chardfield vs integerfield)

When the backend builds the schema, the all_searchfields() function returns all fields where the key of the dictionary is the field name:
```
self.build_schema(connections[self.connection_alias].get_unified_index().all_searchfields())
```

Simply changing the field names to have a different name workarounds the problem. The problem in the first place is noticing what is going on.

## Steps to reproduce the behaviour

1. Configure two search indexes that have a field with the same name but different type. Example below with the "code" field
2. Build the index

```
class ModelAIndex(indexes.SearchIndex, indexes.Indexable):
    text = indexes.CharField(document=True, use_template=True)
    code = indexes.IntegerField(model_attr='code')

    def get_model(self):
        return ModelA

class ModelBIndex(indexes.SearchIndex, indexes.Indexable):
    text = indexes.CharField(document=True, use_template=True)
    code = indexes.CharField(model_attr='code')

    def get_model(self):
        return ModelB
```

## Configuration

* Operating system version: 
* Search engine version: whoosh 2.5.7
* Python version: 3.6.5
* Django version: 1.11.16
* Haystack version: 2.8.1

Stack trace:
```
ValueError while preparing object for update
Traceback (most recent call last):
  File "/project/.direnv/python-3.6.5/lib/python3.6/site-packages/haystack/backends/whoosh_backend.py", line 205, in update
    writer.update_document(**doc)
  File "/project/.direnv/python-3.6.5/lib/python3.6/site-packages/whoosh/writing.py", line 1031, in update_document
    self._record("update_document", args, kwargs)
  File "/project/.direnv/python-3.6.5/lib/python3.6/site-packages/whoosh/writing.py", line 1008, in _record
    getattr(self.writer, method)(*args, **kwargs)
  File "/project/.direnv/python-3.6.5/lib/python3.6/site-packages/whoosh/writing.py", line 477, in update_document
    self.add_document(**fields)
  File "/project/.direnv/python-3.6.5/lib/python3.6/site-packages/whoosh/writing.py", line 754, in add_document
    for tbytes, freq, weight, vbytes in items:
  File "/project/.direnv/python-3.6.5/lib/python3.6/site-packages/whoosh/fields.py", line 558, in index
    yield (self.to_bytes(num, shift), 1, 1.0, emptybytes)
  File "/project/.direnv/python-3.6.5/lib/python3.6/site-packages/whoosh/fields.py", line 611, in to_bytes
    x = self.prepare_number(x)
  File "/project/.direnv/python-3.6.5/lib/python3.6/site-packages/whoosh/fields.py", line 574, in prepare_number
    x = self.numtype(x)
ValueError: invalid literal for int() with base 10: '1 18'
```

**Comment by acdha** [comment]
This working as designed: Haystack builds an index for every registered model so the field names cannot have different types. You can either override the index fieldname for one of them or use the [multiple index](https://django-haystack.readthedocs.io/en/master/multiple_index.html) system to switch indexes if your data types are irreconcilable.
