### ISSUE TITLE
can't update index with workers

### ISSUE THREAD

**Issue by fnsne** [django-haystack/django-haystack#1650]
* [ ] Tested with the latest Haystack release
* [ ] Tested with the current Haystack master branch

## Expected behaviour
If I use the command `python manage.py update_index--verbosity=2  --workers=3` , it should run mulitprocessing to update index.

## Actual behaviour
But, when I actual run `python manage.py update_index --verbosity=2 --workers=3`, I got error below.
```
[INFO/SpawnPoolWorker-3] child process calling self.run()
[INFO/SpawnPoolWorker-1] child process calling self.run()
[INFO/SpawnPoolWorker-2] child process calling self.run()
Process SpawnPoolWorker-3:
Process SpawnPoolWorker-1:
Traceback (most recent call last):
Traceback (most recent call last):
  File "c:\users\watas\appdata\local\programs\python\python36-32\Lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "c:\users\watas\appdata\local\programs\python\python36-32\Lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "c:\users\watas\appdata\local\programs\python\python36-32\Lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\watas\appdata\local\programs\python\python36-32\Lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\watas\appdata\local\programs\python\python36-32\Lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "c:\users\watas\appdata\local\programs\python\python36-32\Lib\multiprocessing\pool.py", line 108, in worker
    task = get()
Process SpawnPoolWorker-2:
  File "c:\users\watas\appdata\local\programs\python\python36-32\Lib\multiprocessing\queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "c:\users\watas\appdata\local\programs\python\python36-32\Lib\multiprocessing\queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\watas\Documents\code\InteRed-2018\creators\models.py", line 6, in <module>
    class Channel(models.Model):
  File "C:\Users\watas\Documents\code\InteRed-2018\creators\models.py", line 6, in <module>
    class Channel(models.Model):
  File "C:\Users\watas\Documents\code\dj_env\lib\site-packages\django\db\models\base.py", line 100, in __new__
    app_config = apps.get_containing_app_config(module)
  File "C:\Users\watas\Documents\code\dj_env\lib\site-packages\django\db\models\base.py", line 100, in __new__
    app_config = apps.get_containing_app_config(module)
  File "C:\Users\watas\Documents\code\dj_env\lib\site-packages\django\apps\registry.py", line 244, in get_containing_app_config
    self.check_apps_ready()
Traceback (most recent call last):
  File "C:\Users\watas\Documents\code\dj_env\lib\site-packages\django\apps\registry.py", line 244, in get_containing_app_config
    self.check_apps_ready()
  File "C:\Users\watas\Documents\code\dj_env\lib\site-packages\django\apps\registry.py", line 127, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
  File "c:\users\watas\appdata\local\programs\python\python36-32\Lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\watas\Documents\code\dj_env\lib\site-packages\django\apps\registry.py", line 127, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
  File "c:\users\watas\appdata\local\programs\python\python36-32\Lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
  File "c:\users\watas\appdata\local\programs\python\python36-32\Lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "c:\users\watas\appdata\local\programs\python\python36-32\Lib\multiprocessing\queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\watas\Documents\code\InteRed-2018\creators\models.py", line 6, in <module>
    class Channel(models.Model):
  File "C:\Users\watas\Documents\code\dj_env\lib\site-packages\django\db\models\base.py", line 100, in __new__
    app_config = apps.get_containing_app_config(module)
  File "C:\Users\watas\Documents\code\dj_env\lib\site-packages\django\apps\registry.py", line 244, in get_containing_app_config
    self.check_apps_ready()
  File "C:\Users\watas\Documents\code\dj_env\lib\site-packages\django\apps\registry.py", line 127, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```
And if not using --workers, it run well.

## Steps to reproduce the behaviour

1. run `python manage.py build_index --verbosity=2 --workers=3`

## Configuration
Django = 2.0.3
django-haystack = 2.8.1
python = 3.6.4
Used in  Virtualenv 16.1.0

* Operating system version:
* Search engine version:
* Python version:
* Django version:
* Haystack version:

**Comment by fnsne** [comment]
I found that using Elasticsearch 5.X is faster than 1.X.
But after building the index,  I just found that haystack is not supporting Elasticsearch 5.X now.
And the master branch of haystack can't run without GDAL.

**Comment by mfxuus** [comment]
same here on 
- Windows 10
- Django 1.8.7
- Python 3.5.4
- django-haystack = 2.5

Any ideas? Thanks!

**Comment by emmm2333** [comment]
When I set up worker = 2 or the number of workers is greater than or equal to 2, there are no errors in executing the program, but there will be some data that can not be searched. Have you solved it?

**Comment by emmm2333** [comment]
My email address ：lishuaijiang@yeah.net

**Comment by fnsne** [comment]
@emmm2333  Hello. I just change to using elasticsearch_dsl instead. And the speed is enough for me. Sorry for not being able to help.

**Comment by emmm2333** [comment]
All right.Thank you all the same 
On 04/25/2019 19:20, fnsne wrote:

@emmm2333 Hello. I just change to using elasticsearch_dsl instead. And the speed is enough for me. Sorry for not being able to help.

**Comment by ajslater** [comment]
### Why
This is happening for me on macOS, I think because of the Python 3.8 change where the multiprocessing start method was changed to spawn from fork. A forked process inherits most of the context of the parent process where a spawned one does not.

### A Proper FIx
A proper fix might be to declare or import the settings environment variable and run django.setup() in haystack.management.command.update_index.update_worker() function so the application is setup and can access django models other created context.

### Workaround
However, it's a bit easier to import a monkeypatch file that forces python multiprocessing to fork in the start of any of the haystack management command files you want to use:
```
import platform          
from multiprocessing import set_start_method  

if platform.system() == "Darwin":  
    set_start_method("fork", force=True)    
```

There are reasons for the python 3.8 change, so the workaround might not be suitable for all users. Also, in some cases `OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES` can bandaid some types of macOS crashes using fork().
