### ISSUE TITLE
"missing 1 required keyword-only argument: 'manager'" error after trying update_index

### ISSUE THREAD

**Issue by panpanick** [django-haystack/django-haystack#1651]
* [x] Tested with the latest Haystack release
* [x] Tested with the current Haystack master branch

## Expected behaviour
This should have successfully built the indexes, then allowed them to be searchable in the app.

## Actual behaviour
During the process of building indexes, it exits with this error
```
missing 1 required keyword-only argument: 'manager'
```

## Steps to reproduce the behaviour

1. Follow this guide https://django-haystack.readthedocs.io/en/master/tutorial.html#installation all the way to the `ReIndex` step
2. run either `./manage.py rebuild_index` or `./manage.py update_index`

## Configuration

* Operating system version: Ubuntu 18.04.1 LTS x86_64
* Search engine version: Whoosh 2.7.4
* Python version: 3.6.6
* Django version: 2.1.3
* Haystack version: 2.8.1

This is the stacktrace output:
```
[ERROR/MainProcess] Failed indexing 1 - 6 (retry 5/5): __call__() missing 1 required keyword-only argument: 'manager' (pid 27136): __call__() missing 1 required keyword-only argument: 'manager'
Traceback (most recent call last):
  File "/home/roli/Env/phobeus_env/lib/python3.6/site-packages/haystack/management/commands/update_index.py", line 97, in do_update
    backend.update(index, current_qs, commit=commit)
  File "/home/roli/Env/phobeus_env/lib/python3.6/site-packages/haystack/backends/whoosh_backend.py", line 185, in update
    doc = index.full_prepare(obj)
  File "/home/roli/Env/phobeus_env/lib/python3.6/site-packages/haystack/indexes.py", line 208, in full_prepare
    self.prepared_data = self.prepare(obj)
  File "/home/roli/Env/phobeus_env/lib/python3.6/site-packages/haystack/indexes.py", line 199, in prepare
    self.prepared_data[field.index_fieldname] = field.prepare(obj)
  File "/home/roli/Env/phobeus_env/lib/python3.6/site-packages/haystack/fields.py", line 206, in prepare
    return self.convert(super(CharField, self).prepare(obj))
  File "/home/roli/Env/phobeus_env/lib/python3.6/site-packages/haystack/fields.py", line 88, in prepare
    values = self.resolve_attributes_lookup(current_objects, attrs)
  File "/home/roli/Env/phobeus_env/lib/python3.6/site-packages/haystack/fields.py", line 132, in resolve_attributes_lookup
    values.append(current_object())
TypeError: __call__() missing 1 required keyword-only argument: 'manager'
[ERROR/MainProcess] Error updating roma using default 
Traceback (most recent call last):
  File "/home/roli/Env/phobeus_env/lib/python3.6/site-packages/haystack/management/commands/update_index.py", line 230, in handle
    self.update_backend(label, using)
  File "/home/roli/Env/phobeus_env/lib/python3.6/site-packages/haystack/management/commands/update_index.py", line 276, in update_backend
    last_max_pk=max_pk)
  File "/home/roli/Env/phobeus_env/lib/python3.6/site-packages/haystack/management/commands/update_index.py", line 97, in do_update
    backend.update(index, current_qs, commit=commit)
  File "/home/roli/Env/phobeus_env/lib/python3.6/site-packages/haystack/backends/whoosh_backend.py", line 185, in update
    doc = index.full_prepare(obj)
  File "/home/roli/Env/phobeus_env/lib/python3.6/site-packages/haystack/indexes.py", line 208, in full_prepare
    self.prepared_data = self.prepare(obj)
  File "/home/roli/Env/phobeus_env/lib/python3.6/site-packages/haystack/indexes.py", line 199, in prepare
    self.prepared_data[field.index_fieldname] = field.prepare(obj)
  File "/home/roli/Env/phobeus_env/lib/python3.6/site-packages/haystack/fields.py", line 206, in prepare
    return self.convert(super(CharField, self).prepare(obj))
  File "/home/roli/Env/phobeus_env/lib/python3.6/site-packages/haystack/fields.py", line 88, in prepare
    values = self.resolve_attributes_lookup(current_objects, attrs)
  File "/home/roli/Env/phobeus_env/lib/python3.6/site-packages/haystack/fields.py", line 132, in resolve_attributes_lookup
    values.append(current_object())
TypeError: __call__() missing 1 required keyword-only argument: 'manager'
Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/roli/Env/phobeus_env/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/roli/Env/phobeus_env/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/roli/Env/phobeus_env/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/roli/Env/phobeus_env/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/roli/Env/phobeus_env/lib/python3.6/site-packages/haystack/management/commands/rebuild_index.py", line 42, in handle
    call_command('update_index', **update_options)
  File "/home/roli/Env/phobeus_env/lib/python3.6/site-packages/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/home/roli/Env/phobeus_env/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/roli/Env/phobeus_env/lib/python3.6/site-packages/haystack/management/commands/update_index.py", line 230, in handle
    self.update_backend(label, using)
  File "/home/roli/Env/phobeus_env/lib/python3.6/site-packages/haystack/management/commands/update_index.py", line 276, in update_backend
    last_max_pk=max_pk)
  File "/home/roli/Env/phobeus_env/lib/python3.6/site-packages/haystack/management/commands/update_index.py", line 97, in do_update
    backend.update(index, current_qs, commit=commit)
  File "/home/roli/Env/phobeus_env/lib/python3.6/site-packages/haystack/backends/whoosh_backend.py", line 185, in update
    doc = index.full_prepare(obj)
  File "/home/roli/Env/phobeus_env/lib/python3.6/site-packages/haystack/indexes.py", line 208, in full_prepare
    self.prepared_data = self.prepare(obj)
  File "/home/roli/Env/phobeus_env/lib/python3.6/site-packages/haystack/indexes.py", line 199, in prepare
    self.prepared_data[field.index_fieldname] = field.prepare(obj)
  File "/home/roli/Env/phobeus_env/lib/python3.6/site-packages/haystack/fields.py", line 206, in prepare
    return self.convert(super(CharField, self).prepare(obj))
  File "/home/roli/Env/phobeus_env/lib/python3.6/site-packages/haystack/fields.py", line 88, in prepare
    values = self.resolve_attributes_lookup(current_objects, attrs)
  File "/home/roli/Env/phobeus_env/lib/python3.6/site-packages/haystack/fields.py", line 132, in resolve_attributes_lookup
    values.append(current_object())
TypeError: __call__() missing 1 required keyword-only argument: 'manager'
```

**Comment by TheRockXu** [comment]
Having the same problem here.

**Comment by TheRockXu** [comment]
I found an ugly fix. The problem is that `values.append(current_object())` doesnt work. So I just went in and replace it as `values.append(current_object)`. The file is located at django-projects/lib/python3.6/site-packages/haystack/fields.py.  Try it and it will work.

**Comment by maxwelld90** [comment]
Hi there,

Appreciate the fix -- has there been a patch released for this issue? Seems to affect 2.0+ versions of Django, at least from my limited testing.

Kind regards!
