### ISSUE TITLE
solr_backend got something error

### ISSUE THREAD

**Issue by zcmiao190** [django-haystack/django-haystack#1661]
It seems a Data Type error, but i totally follow the Document usage. 

```code
Internal Server Error: /search
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python36\lib\site-packages\haystack\views.py", line 51, in __call__
    return self.create_response()
  File "C:\Python36\lib\site-packages\haystack\views.py", line 150, in create_response
    context = self.get_context()
  File "C:\Python36\lib\site-packages\haystack\views.py", line 128, in get_context
    (paginator, page) = self.build_page()
  File "C:\Python36\lib\site-packages\haystack\views.py", line 108, in build_page
    self.results[start_offset:start_offset + self.results_per_page]
  File "C:\Python36\lib\site-packages\haystack\query.py", line 307, in __getitem__
    self._fill_cache(start, bound)
  File "C:\Python36\lib\site-packages\haystack\query.py", line 231, in _fill_cache
    results = self.query.get_results(**kwargs)
  File "C:\Python36\lib\site-packages\haystack\backends\__init__.py", line 638, in get_results
    self.run(**kwargs)
  File "C:\Python36\lib\site-packages\haystack\backends\solr_backend.py", line 802, in run
    results = self.backend.search(final_query, **search_kwargs)
  File "C:\Python36\lib\site-packages\haystack\backends\__init__.py", line 33, in wrapper
    return func(obj, query_string, *args, **kwargs)
  File "C:\Python36\lib\site-packages\haystack\backends\solr_backend.py", line 149, in search
    distance_point=kwargs.get('distance_point'))
  File "C:\Python36\lib\site-packages\haystack\backends\solr_backend.py", line 425, in _process_results
    app_label, model_name = raw_result[DJANGO_CT].split('.')
AttributeError: 'list' object has no attribute **'split'**
```

1.

## Configuration

* Operating system version: window 10 Enterprise.
* Search engine version: solr 7.7.0.
* Python version: 3.6.5.
* Django version:  2.1.7.
* Haystack version: 2.8.1.

**Comment by edwardoliveira** [comment]
This looks like a duplicate of both #1200 and #1182 and the solution probably is https://github.com/django-haystack/django-haystack/issues/1182#issuecomment-372600947
