### ISSUE TITLE
FacetedSearchView fails with elasticsearch 7.0.0

### ISSUE THREAD

**Issue by michaelmior** [django-haystack/django-haystack#1671]
* [*] Tested with the latest Haystack release
* [ ] Tested with the current Haystack master branch

## Expected behaviour

Search should work as it does with elasticsearch 6.3.1

## Actual behaviour

I get the exception below

```
Traceback (most recent call last):
  File "/home/travis/build/michaelmior/pylinks/pylinks/search/tests.py", line 20, in test_search
    response = self.client.get(reverse('haystack_search') + '?q=Google')
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/test/client.py", line 535, in get
    response = super().get(path, data=data, secure=secure, **extra)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/test/client.py", line 347, in get
    **extra,
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/test/client.py", line 422, in generic
    return self.request(**r)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/test/client.py", line 503, in request
    raise exc_value
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/python/3.6.3/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/haystack/views.py", line 51, in __call__
    return self.create_response()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/haystack/views.py", line 150, in create_response
    context = self.get_context()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/haystack/views.py", line 128, in get_context
    (paginator, page) = self.build_page()
  File "/home/travis/build/michaelmior/pylinks/pylinks/search/views.py", line 31, in build_page
    page = paginator.page(page_number)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/core/paginator.py", line 70, in page
    number = self.validate_number(number)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/core/paginator.py", line 48, in validate_number
    if number > self.num_pages:
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/core/paginator.py", line 97, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/core/paginator.py", line 91, in count
    return c()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/haystack/query.py", line 522, in count
    return len(self)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/haystack/query.py", line 86, in __len__
    self._result_count = self.query.get_count()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/haystack/backends/__init__.py", line 619, in get_count
    self.run()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/haystack/backends/elasticsearch_backend.py", line 951, in run
    results = self.backend.search(final_query, **search_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/haystack/backends/__init__.py", line 33, in wrapper
    return func(obj, query_string, *args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/haystack/backends/elasticsearch_backend.py", line 524, in search
    _source=True)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
TypeError: search() got an unexpected keyword argument 'doc_type'
```

## Steps to reproduce the behaviour

1. Create a FacetedSearchView with elasticsearch 7.0.0 as the backend

Repo with the failing code here: http://github.com/michaelmior/pylinks/

## Configuration

* Python version: 3.6
* Django version: 2.2
* Haystack version: 2.8.1

**Comment by acdha** [comment]
ElasticSearch breaks backwards compatibility pretty routinely and we haven't had much luck in finding someone who wants to maintain Haystack support for it, which is why the docs don't list that version as supported:

http://docs.haystacksearch.org/en/master/installing_search_engines.html#elasticsearch

If you want to contribute a pull request I'm sure the other ElasticSearch users would appreciate it.

**Comment by michaelmior** [comment]
Got it. Thanks for clarifying. I'll try to take a look at some point over the next few weeks but this isn't high priority for me.

**Comment by michaelmior** [comment]
@acdha Quick question. I can't quickly tell from looking through the source or history. I see there are several backends for various ES versions. Is the preference that `elasticsearch` backend be for the most recent ES version or for the oldest supported ES version? That is, for ES7 support, should I create a new `elasticsearch7` backend or rename the `elasticsearch` backend to `elasticsearch6` and then support ES7 with the `elasticsearch` backend?

**Comment by acdha** [comment]
We need to sort that out, along with deprecating the older versions, but my thought is that the backend version should match the major ES version — i.e. `elasticsearch7`, presumably starting from `elasticsearch5`.

**Comment by michaelmior** [comment]
Do you know what the current `elasticsearch` backend is designed to support? It works for me with ES6.

**Comment by acdha** [comment]
I believe that's the legacy 1.x version — IIRC, the problem has been that the backends _mostly_ work but a few features will break.

**Comment by josernestodavila** [comment]
This issue is not only for `FacetedSearchView`, I just hit this wall using the `SearchModelAdminMixin` with ES7, Python 3.7.4, Django 2.2 and Haystack 2.8.1.

**Comment by Rafalonso** [comment]
@josernestodavila Looking into the engines should be the starting point.
For OP's problem specifically, ES has removed document types. 
https://www.elastic.co/guide/en/elasticsearch/reference/7.x/removal-of-types.html
