### ISSUE TITLE
parsing_exception', '[query_string] query does not support [auto_generate_phrase_queries]

### ISSUE THREAD

**Issue by wangoloj** [django-haystack/django-haystack#1713]
Am stack in a middle of a complete project only implementing the search is remaining, But I was finialzing with realtime search I got this error

```
Failed to query Elasticsearch using 'description_auto:(Weekly)': TransportError(400, 'parsing_exception', '[query_string] query does not support [auto_generate_phrase_queries]')
Traceback (most recent call last):
  File "/home/wangolo/Templates/virtualenv/www.lumioticticketting.com/lib/python3.7/site-packages/haystack_elasticsearch/elasticsearch.py", line 565, in search
    _source=True)
  File "/home/wangolo/Templates/virtualenv/www.lumioticticketting.com/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/wangolo/Templates/virtualenv/www.lumioticticketting.com/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 632, in search
    doc_type, '_search'), params=params, body=body)
  File "/home/wangolo/Templates/virtualenv/www.lumioticticketting.com/lib/python3.7/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/wangolo/Templates/virtualenv/www.lumioticticketting.com/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 129, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/wangolo/Templates/virtualenv/www.lumioticticketting.com/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'parsing_exception', '[query_string] query does not support [auto_generate_phrase_queries]')
HTTP GET /rtsearch/autocomplete/?q=Weekly 200 [0.03, 127.0.0.1:53478]
```

**Comment by girzel** [comment]
FWIW, I got this only due to a version mismatch between elasticsearch (system package), haystack, and elasticsearch (python package). Once the versions all lined up it went away.
