### ISSUE TITLE
build_solr_schema doesn't generate all field nodes

### ISSUE THREAD

**Issue by thomasrea0113** [django-haystack/django-haystack#1715]
* [ ] Tested with the latest Haystack release
* [ ] Tested with the current Haystack master branch

I picked this project up from a vendor, and and stuck using 2.7.x because we are still using django 1.10.

## Expected behaviour

```
root@4abc302f98f0:/code# python manage.py rebuild_index --noinput
Removing all documents from your index because you said so.
All documents removed.
Indexing 1 components
Indexing 1 projects
Indexing 2 requests
Indexing 1 lab forms
```

## Actual behaviour

```
root@4abc302f98f0:/code# python manage.py rebuild_index --noinput
Removing all documents from your index because you said so.
All documents removed.
Indexing 1 components
Indexing 1 projects
Indexing 2 requests
Failed to add documents to Solr: Solr responded with an error (HTTP 400): [Reason: ERROR: [doc=requests.request.1] unknown field 'state']
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/haystack/backends/solr_backend.py", line 76, in update
    self.conn.add(docs, commit=commit, boost=index.get_field_weights())
  File "/usr/local/lib/python3.5/site-packages/pysolr.py", line 891, in add
    overwrite=overwrite, handler=handler)
  File "/usr/local/lib/python3.5/site-packages/pysolr.py", line 478, in _update
    return self._send_request('post', path, message, {'Content-type': 'text/xml; charset=utf-8'})
  File "/usr/local/lib/python3.5/site-packages/pysolr.py", line 393, in _send_request
    raise SolrError(error_message % (resp.status_code, solr_message))
pysolr.SolrError: Solr responded with an error (HTTP 400): [Reason: ERROR: [doc=requests.request.1] unknown field 'state']
Indexing 1 lab forms
```

## Steps to reproduce the behaviour

1. setup solr 6.6.6 and connect to a django 1.10 application

2. Index:
```python

class RequestIndex(indexes.SearchIndex, indexes.Indexable):
    text = indexes.CharField(document=True, use_template=True)
    type = 'Request'

    # FIXME WHY DOESNT BUILD_SOLR_SCHEMA PICK UP THIS FIELD
    lab_form_type = indexes.IntegerField(model_attr='lab_form_type_id')

    customer = indexes.IntegerField(model_attr='customer_id', null=True)
    request_id = IntegerListField(model_attr='id')
    request_name = indexes.CharField(model_attr='name', boost=1.3)
    owner = indexes.IntegerField(model_attr='creator_id')
    lab = indexes.IntegerField(model_attr='lab_id', null=True)
    status = indexes.IntegerField(model_attr='status_id')
    component_name = indexes.EdgeNgramField(null=True, boost=1.1)
    description = indexes.CharField()
    comment = indexes.CharField()
    request_form = indexes.CharField()
    response_form = indexes.CharField()

    def get_model(self):
        return Request

```

I noticed that even when I comment the existing fields, the generated schema still includes them. I've tested by manually modifying the solr schema to include `<field name="lab_form_type_id" type="long" indexed="true" stored="true" multiValued="true" />` and it works exactly as expected.

Where are these fields inferred from, and why does commenting them out still cause them to be generated in the schema?

## Configuration

* Operating system version: python:3.8 docker container
* Search engine version: solr 6.6.6
* Python version: 3.5.9
* Django version: 1.10
* Haystack version: 2.7

**Comment by thomasrea0113** [comment]
closing because I should have fully read the docs.

There was a schema.xml file in the `search_configuration` folder which was explicitily setting the field types. Removing that template revealed the issue.

**Comment by acdha** [comment]
If there's something which the documentation could have made easier to find, I'm open to pull requests — we've always needed more time for docs.
