### ISSUE TITLE
[ERROR/MainProcess] Failed indexing 1 - 2 (retry 5/5): search/indexes/posts/post_text.txt (pid 1352): search/indexes/posts/post_text.txt

### ISSUE THREAD

**Issue by khaldon** [django-haystack/django-haystack#1726]
`WARNING: This will irreparably remove EVERYTHING from your search index in connection 'default'.
Your choices after this are to restore from backups or rebuild via the rebuild_index command.
Are you sure you wish to continue? [y/N] y
Removing all documents from your index because you said so.
All documents removed.
Indexing 2 posts
[ERROR/MainProcess] Failed indexing 1 - 2 (retry 5/5): search/indexes/posts/post_text.txt (pid 1352): search/indexes/posts/post_text.txt
Traceback (most recent call last):
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/haystack/management/commands/update_index.py", line 97, in do_update
    backend.update(index, current_qs, commit=commit)
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/haystack/backends/whoosh_backend.py", line 185, in update
    doc = index.full_prepare(obj)
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/haystack/indexes.py", line 208, in full_prepare
    self.prepared_data = self.prepare(obj)
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/haystack/indexes.py", line 199, in prepare
    self.prepared_data[field.index_fieldname] = field.prepare(obj)
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/haystack/fields.py", line 206, in prepare
    return self.convert(super(CharField, self).prepare(obj))
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/haystack/fields.py", line 83, in prepare
    return self.prepare_template(obj)
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/haystack/fields.py", line 183, in prepare_template
    t = loader.select_template(template_names)
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: search/indexes/posts/post_text.txt
[ERROR/MainProcess] Error updating posts using default 
Traceback (most recent call last):
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/haystack/management/commands/update_index.py", line 230, in handle
    self.update_backend(label, using)
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/haystack/management/commands/update_index.py", line 276, in update_backend
    last_max_pk=max_pk)
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/haystack/management/commands/update_index.py", line 97, in do_update
    backend.update(index, current_qs, commit=commit)
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/haystack/backends/whoosh_backend.py", line 185, in update
    doc = index.full_prepare(obj)
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/haystack/indexes.py", line 208, in full_prepare
    self.prepared_data = self.prepare(obj)
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/haystack/indexes.py", line 199, in prepare
    self.prepared_data[field.index_fieldname] = field.prepare(obj)
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/haystack/fields.py", line 206, in prepare
    return self.convert(super(CharField, self).prepare(obj))
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/haystack/fields.py", line 83, in prepare
    return self.prepare_template(obj)
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/haystack/fields.py", line 183, in prepare_template
    t = loader.select_template(template_names)
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: search/indexes/posts/post_text.txt
Traceback (most recent call last):
  File "./manage.py", line 21, in <module>
    main()
  File "./manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/haystack/management/commands/rebuild_index.py", line 42, in handle
    call_command('update_index', **update_options)
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/haystack/management/commands/update_index.py", line 230, in handle
    self.update_backend(label, using)
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/haystack/management/commands/update_index.py", line 276, in update_backend
    last_max_pk=max_pk)
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/haystack/management/commands/update_index.py", line 97, in do_update
    backend.update(index, current_qs, commit=commit)
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/haystack/backends/whoosh_backend.py", line 185, in update
    doc = index.full_prepare(obj)
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/haystack/indexes.py", line 208, in full_prepare
    self.prepared_data = self.prepare(obj)
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/haystack/indexes.py", line 199, in prepare
    self.prepared_data[field.index_fieldname] = field.prepare(obj)
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/haystack/fields.py", line 206, in prepare
    return self.convert(super(CharField, self).prepare(obj))
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/haystack/fields.py", line 83, in prepare
    return self.prepare_template(obj)
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/haystack/fields.py", line 183, in prepare_template
    t = loader.select_template(template_names)
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: search/indexes/posts/post_text.txt
`

**Comment by acdha** [comment]
This looks like a problem in your local setup. Please re-open if you can make a clean report following the instructions.
