### ISSUE TITLE
'SolrSearchBackend' object has no attribute 'reload'

### ISSUE THREAD

**Issue by PhamTrongVan** [django-haystack/django-haystack#1741]
* [ ] Tested with the latest Haystack release

## Expected behaviour
Can reload a Solr core 
## Actual behaviour
Trying to write schema file located at ./templates/search_configuration/conf/schema.xml
2020-08-13 08:55:38,962 - [bugsnag] WARNING - No API key configured, couldn't notify
WARNING 2020-08-13 08:55:38,962 client 46 139620787420488 No API key configured, couldn't notify
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/haystack/management/commands/build_solr_schema.py", line 67, in handle
    connections[using].get_backend().reload()
AttributeError: 'SolrSearchBackend' object has no attribute 'reload'
## Steps to reproduce the behaviour
1. Config haystack connection: 
    HAYSTACK_CONNECTIONS = {
        "default": {
            "ENGINE": "aystack.backends.solr_backend.SolrEngine",
            "URL": "HTTP://localhost:8983/solr/<solr-core>",
            "INCLUDE_SPELLING": False,
            "ADMIN_URL":  "HTTP://localhost:8983/solr/admin/cores"
        },
    }
2. Run command: python manage.py build_solr_schema -c <dir_conf>/conf -f <dir_conf>/conf/schema.xml -r <sorl-core>

## Configuration

* Operating system version: Win 10/ Ubuntu 20.04
* Search engine version: Solr 8.6.0
* Python version: 3.6.8
* Django version: 2.2.7
* Haystack version: 2.8.1

**Comment by Andrew-Chen-Wang** [comment]
@PhamTrongVan I took a look at the source code: it seems like there is no method `reload`. In your management command, just remove the `-r` flag.
