### ISSUE TITLE
django.template.exceptions.TemplateDoesNotExist: search/indexes/blog/note_text.txt

### ISSUE THREAD

**Issue by cs246810** [django-haystack/django-haystack#1804]
* [x] Tested with the latest Haystack release

```shell
(venv) congshi@congshideMacBook-Air DHTutorial % python manage.py rebuild_index
WARNING: This will irreparably remove EVERYTHING from your search index in connection 'default'.
Your choices after this are to restore from backups or rebuild via the `rebuild_index` command.
Are you sure you wish to continue? [y/N] y
Removing all documents from your index because you said so.
All documents removed.
/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1416: RuntimeWarning: DateTimeField Note.pub_date received a naive datetime (2021-07-09 07:45:43.129405) while time zone support is active.
  warnings.warn("DateTimeField %s received a naive datetime (%s)"
Indexing 3 notes
[ERROR/MainProcess] Failed indexing 1 - 3 (retry 5/5): search/indexes/blog/note_text.txt (pid 68311): search/indexes/blog/note_text.txt
Traceback (most recent call last):
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/haystack/management/commands/update_index.py", line 111, in do_update
    backend.update(index, current_qs, commit=commit)
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/haystack/backends/whoosh_backend.py", line 269, in update
    doc = index.full_prepare(obj)
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/haystack/indexes.py", line 236, in full_prepare
    self.prepared_data = self.prepare(obj)
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/haystack/indexes.py", line 227, in prepare
    self.prepared_data[field.index_fieldname] = field.prepare(obj)
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/haystack/fields.py", line 235, in prepare
    return self.convert(super(CharField, self).prepare(obj))
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/haystack/fields.py", line 99, in prepare
    return self.prepare_template(obj)
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/haystack/fields.py", line 212, in prepare_template
    t = loader.select_template(template_names)
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: search/indexes/blog/note_text.txt
[ERROR/MainProcess] Error updating blog using default 
Traceback (most recent call last):
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/haystack/management/commands/update_index.py", line 274, in handle
    self.update_backend(label, using)
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/haystack/management/commands/update_index.py", line 319, in update_backend
    max_pk = do_update(
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/haystack/management/commands/update_index.py", line 111, in do_update
    backend.update(index, current_qs, commit=commit)
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/haystack/backends/whoosh_backend.py", line 269, in update
    doc = index.full_prepare(obj)
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/haystack/indexes.py", line 236, in full_prepare
    self.prepared_data = self.prepare(obj)
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/haystack/indexes.py", line 227, in prepare
    self.prepared_data[field.index_fieldname] = field.prepare(obj)
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/haystack/fields.py", line 235, in prepare
    return self.convert(super(CharField, self).prepare(obj))
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/haystack/fields.py", line 99, in prepare
    return self.prepare_template(obj)
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/haystack/fields.py", line 212, in prepare_template
    t = loader.select_template(template_names)
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: search/indexes/blog/note_text.txt
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/haystack/management/commands/rebuild_index.py", line 66, in handle
    call_command("update_index", **update_options)
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/haystack/management/commands/update_index.py", line 274, in handle
    self.update_backend(label, using)
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/haystack/management/commands/update_index.py", line 319, in update_backend
    max_pk = do_update(
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/haystack/management/commands/update_index.py", line 111, in do_update
    backend.update(index, current_qs, commit=commit)
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/haystack/backends/whoosh_backend.py", line 269, in update
    doc = index.full_prepare(obj)
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/haystack/indexes.py", line 236, in full_prepare
    self.prepared_data = self.prepare(obj)
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/haystack/indexes.py", line 227, in prepare
    self.prepared_data[field.index_fieldname] = field.prepare(obj)
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/haystack/fields.py", line 235, in prepare
    return self.convert(super(CharField, self).prepare(obj))
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/haystack/fields.py", line 99, in prepare
    return self.prepare_template(obj)
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/haystack/fields.py", line 212, in prepare_template
    t = loader.select_template(template_names)
  File "/Users/congshi/PycharmProjects/DHTutorial/venv/lib/python3.8/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: search/indexes/blog/note_text.txt
(venv) congshi@congshideMacBook-Air DHTutorial % 
```
This is Project Structure in IDE(Pycharm):
![image](https://user-images.githubusercontent.com/86016274/125043010-16c72700-e0cd-11eb-9ad3-254a4c6175d4.png)

Everything looks correct. But `django.template.exceptions.TemplateDoesNotExist: search/indexes/blog/note_text.txt`.

**Comment by cs246810** [comment]
Click this link [issue](https://github.com/cs246810/DHTutorial) view the detail.

**Comment by cs246810** [comment]
Click this link [issue](https://github.com/cs246810/DHTutorial) view the detail.

**Comment by acdha** [comment]
It looks like you're trying to have `blog/search/indexes/blog/note_text.txt` loaded as `search/indexes/blog/note_text.txt`. You'd either need to add the `blog/templates` directory to the template loader's list or move `blog/templates/search` to `templates/search` and make sure that directory is in your template path.

https://docs.djangoproject.com/en/3.2/ref/settings/#std:setting-TEMPLATES

https://docs.djangoproject.com/en/3.2/ref/templates/api/#loading-templates

**Comment by cs246810** [comment]
Thanks for your reply. This is my error. 
```python
'note_text.txt' != 'note_text.txt '
```
So file not found.

**Comment by acdha** [comment]
Oh, thanks for updating that — very easy to miss.
