### ISSUE TITLE
Cannot change DocValues type from SORTED_SET to SORTED for field "django_ct"

### ISSUE THREAD

**Issue by JulienPalard** [django-haystack/django-haystack#1972]
Hi!

I'm very new to Django Haystack sorry if I missed something obvious :D and sorry my setup is already no that simple with Django Oscar and DRF, I could have started... with less...

* [x] Tested with the latest Haystack release
* [x] Tested with the current Haystack master branch

## Expected behaviour

No exception while reindexing :)

## Actual behaviour

```shell
$ /opt/website/venv/bin/python /opt/website/src/manage.py rebuild_index
WARNING: This will irreparably remove EVERYTHING from your search index in connection 'default'.
Your choices after this are to restore from backups or rebuild via the `rebuild_index` command.
Are you sure you wish to continue? [y/N] y
Removing all documents from your index because you said so.
Finished 'http://127.0.0.1:8983/solr/testing/update/?commit=true' (post) with body '<delete><q' in 0.014 seconds, with status 200
Finished 'http://127.0.0.1:8983/solr/testing/update/?commit=true' (post) with body '<optimize ' in 0.003 seconds, with status 200
All documents removed.
Indexing 2697 Products
Finished 'http://127.0.0.1:8983/solr/testing/update/?commit=true' (post) with body '<add><doc>' in 0.054 seconds, with status 400
Solr responded with an error (HTTP 400): [Reason: Exception writing document id catalogue.product.32 to the index; possible analysis error: cannot change DocValues type from SORTED_SET to SORTED for field "django_ct"]
Failed to add documents to Solr
Traceback (most recent call last):
  File "/opt/website/venv/lib/python3.11/site-packages/haystack/backends/solr_backend.py", line 101, in update
    self.conn.add(docs, commit=commit, boost=index.get_field_weights())
  File "/opt/website/venv/lib/python3.11/site-packages/pysolr.py", line 1042, in add
    return self._update(
           ^^^^^^^^^^^^^
  File "/opt/website/venv/lib/python3.11/site-packages/pysolr.py", line 564, in _update
    return self._send_request(
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/website/venv/lib/python3.11/site-packages/pysolr.py", line 463, in _send_request
    raise SolrError(error_message % (resp.status_code, solr_message))
pysolr.SolrError: Solr responded with an error (HTTP 400): [Reason: Exception writing document id catalogue.product.32 to the index; possible analysis error: cannot change DocValues type from SORTED_SET to SORTED for field "django_ct"]
```

I'm very new to `django-haystack` and `solr`, so I may have miseed something obvious, and I don't understand the provided error.

## Steps to reproduce the behaviour

I'm providing "big" steps, probably hard to follow, tell me if you need a reproducer in the form of a clonable git repo or something.

1. Setup a venv :)
1. `pip install django==4.2.13 django-haystack==3.3.0 pysolr==3.9.0 django-oscar==3.2.4 drf_haystack==1.8.13
2. Get some code: `git clone https://github.com/django-oscar/django-oscar.git`
3. `cd django-oscar`
4. `make sandbox`
4. Create a `search.py` file in a Django app:

```python
from drf_haystack.mixins import FacetMixin
from drf_haystack.serializers import HaystackFacetSerializer, HaystackSerializerMixin
from drf_haystack.viewsets import HaystackViewSet
from oscar.apps.search.search_indexes import ProductIndex
from oscar.core.loading import get_model
from oscarapi.utils.loading import get_api_class
from rest_framework.routers import SimpleRouter

ProductLinkSerializer = get_api_class("serializers.product", "ProductLinkSerializer")
Product = get_model("catalogue", "Product")


class ProductSearchSerializer(HaystackSerializerMixin, ProductLinkSerializer):

    class Meta(ProductLinkSerializer.Meta):
        index_classes = [ProductIndex]
        field_aliases = {"q": "title"}


class ProductFacetSerializer(HaystackFacetSerializer):
    serialize_objects = False  # Setting this to True will serialize the
    class Meta:
        index_classes = [ProductIndex]
        fields = ["upc", "title", "cateogory"]
        field_options = {"upc": {}, "title": {}, "cateogry": {}}


class ProductSearchView(HaystackViewSet, FacetMixin):
    index_models = [Product]
    facet_serializer_class = ProductFacetSerializer
    serializer_class = ProductSearchSerializer


router = SimpleRouter()
router.register("search", ProductSearchView, basename="product_search")

urlpatterns = router.urls
```

7. Configure Django to use Solr

```python
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.solr_backend.SolrEngine',
        'URL': 'http://127.0.0.1:8983/solr/testing',
        'ADMIN_URL': 'http://127.0.0.1:8983/solr/admin/cores',
        'INCLUDE_SPELLING': True,
    },
}
```

8. Create the core `./bin/solr create -c testing -n basic_config`
9. Build solr schema `sudo -u website /opt/website/venv/bin/python /opt/website/src/manage.py build_solr_schema --configure-directory=/opt/solr/solr-6.6.6/server/solr/testing/conf --reload-core testing`
10. Reindex : `sudo -u website /opt/website/venv/bin/python /opt/website/src/manage.py rebuild_index`

The exception occurs while reindexing.

## Configuration

* Operating system version: Debian 12
* Search engine version: Solr 6.6.6
* Python version: 3.11.2
* Django version: 4.2
* Haystack version: 3.2.1
* django-oscar 3.2.4
* pysolr 3.9.0
* drf-haystack 1.8.13

**Comment by JulienPalard** [comment]
Hi.

Today it works.

Be happy :)
