### ISSUE TITLE
Simplebackend unable to perform basic searches.

### ISSUE THREAD

**Issue by kitsunde** [django-haystack/django-haystack#657]
Yesterday I was running into #643 which is now foxed, but I still cannot perform any searches using the simple backend.

```
from haystack.query import SearchQuerySet
SearchQuerySet().filter(content='cake')
```

Crashes with:

```
Traceback (most recent call last):
  File "/Users/kitsunde/.virtualenvs/clients/lib/python2.7/site-packages/raven/utils/serializer/manager.py", line 69, in transform
    return self.transform(repr(value))
  File "/Users/kitsunde/.virtualenvs/clients/src/django-haystack/haystack/query.py", line 75, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE])
  File "/Users/kitsunde/.virtualenvs/clients/src/django-haystack/haystack/query.py", line 261, in __getitem__
    self._fill_cache(start, bound)
  File "/Users/kitsunde/.virtualenvs/clients/src/django-haystack/haystack/query.py", line 159, in _fill_cache
    results = self.query.get_results(**kwargs)
  File "/Users/kitsunde/.virtualenvs/clients/src/django-haystack/haystack/backends/__init__.py", line 484, in get_results
    self.run(**kwargs)
  File "/Users/kitsunde/.virtualenvs/clients/src/django-haystack/haystack/backends/__init__.py", line 402, in run
    results = self.backend.search(final_query, **search_kwargs)
  File "/Users/kitsunde/.virtualenvs/clients/src/django-haystack/haystack/backends/__init__.py", line 26, in wrapper
    return func(obj, query_string, *args, **kwargs)
  File "/Users/kitsunde/.virtualenvs/clients/src/django-haystack/haystack/backends/simple_backend.py", line 69, in search
    qs = model.objects.filter(reduce(lambda x, y: x|y, queries))
TypeError: reduce() of empty sequence with no initial value
```

**Comment by decibyte** [comment]
@bigjust, can you please have a look and reconsider to open this again? I just bumped into the same problem today. I can provide a test case if necessary. There's even a PR (#954) with a fix for it.

**Comment by bigjust** [comment]
Yes, please add a test case!

**Comment by benvand** [comment]
@bigjust 
Done it here on another fork as per convention.
https://github.com/django-haystack/django-haystack/pull/1475

**Comment by benvand** [comment]
I'll close this PR when the other one is merged.
