### ISSUE TITLE
Unable to rebuild indexes due to bug in error handling

### ISSUE THREAD

**Issue by chrisspen** [django-haystack/django-haystack#668]
I installed the most recent version of django-haystack on Ubuntu 12.04 using:

```
sudo pip install -U https://github.com/toastdriven/django-haystack/tarball/master
```

I have an index like:

```
class MyIndex(indexes.SearchIndex, indexes.Indexable):
    text = indexes.CharField(document=True, use_template=True)

    def get_model(self):
    return MyModel

    def index_queryset(self):
    return self.get_model().objects.all()

    def prepare(self, obj):
    data = super(MyIndex, self).prepare(obj)
    data['boost'] = obj.weight
    return data
```

And I'm using the whoosh backend, with:

```
HAYSTACK_CONNECTIONS = {
    'default': {
    'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
    'PATH': os.path.join(os.path.dirname(__file__), 'whoosh_index'),
    },
}
```

However, when I run `python manage.py rebuild_index`, I get the error:

```
Traceback (most recent call last):
  File "./manage.py", line 35, in <module>
    execute_manager(settings)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 459, in execute_manager
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/haystack/management/commands/rebuild_index.py", line 15, in handle
    call_command('update_index', **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 150, in call_command
    return klass.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/haystack/management/commands/update_index.py", line 170, in handle
    return super(Command, self).handle(*items, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 341, in handle
    label_output = self.handle_label(label, **options)
  File "/usr/local/lib/python2.7/dist-packages/haystack/management/commands/update_index.py", line 229, in handle_label
    do_update(self.backend, index, qs, start, end, total, self.verbosity)
  File "/usr/local/lib/python2.7/dist-packages/haystack/management/commands/update_index.py", line 68, in do_update
    backend.update(index, current_qs)
  File "/usr/local/lib/python2.7/dist-packages/haystack/backends/whoosh_backend.py", line 193, in update
    self.log.error(u"%s while preparing object for update" % e.__name__, exc_info=True, extra={
AttributeError: 'UnknownFieldError' object has no attribute '__name__'
```

**Comment by laffuste** [comment]
Use 
```
data['_boost']
```
instead.
From:
https://github.com/django-haystack/django-haystack/issues/369#issuecomment-130587186
