### ISSUE TITLE
Haystack v2 + Solr + lxml == Exception

### ISSUE THREAD

**Issue by jaddison** [django-haystack/django-haystack#792]
rebuild_index gives the error shown below...

Environment:
- Ubuntu 10.04 server (attempted on Linode and Vagrant Virtualbox VM)
- Django 1.5.x
- Solr 1.4.0
- pysolr 3.0.6
- lxml 3.2.0 (pip installed)
- python 2.6.5

If I remove lxml, everything works fine, the rebuild_index completes fine, however I'm using lxml with BeautifulSoup4 elsewhere in my project. Let me know if I can provide further input.

```python
(localdev)vagrant@localdev:/vagrant$ ./manage.py rebuild_index --noinput --traceback
Removing all documents from your index because you said so.
All documents removed.
Indexing 1860 Locations
Indexing 18952 Events
ERROR:root:Error updating activities using default 
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/localdev/lib/python2.6/site-packages/haystack/management/commands/update_index.py", line 210, in handle_label
    self.update_backend(label, using)
  File "/home/vagrant/.virtualenvs/localdev/lib/python2.6/site-packages/haystack/management/commands/update_index.py", line 256, in update_backend
    do_update(backend, index, qs, start, end, total, self.verbosity)
  File "/home/vagrant/.virtualenvs/localdev/lib/python2.6/site-packages/haystack/management/commands/update_index.py", line 78, in do_update
    backend.update(index, current_qs)
  File "/home/vagrant/.virtualenvs/localdev/lib/python2.6/site-packages/haystack/backends/solr_backend.py", line 66, in update
    self.conn.add(docs, commit=commit, boost=index.get_field_weights())
  File "/home/vagrant/.virtualenvs/localdev/lib/python2.6/site-packages/pysolr.py", line 740, in add
    message.append(self._build_doc(doc, boost=boost))
  File "/home/vagrant/.virtualenvs/localdev/lib/python2.6/site-packages/pysolr.py", line 696, in _build_doc
    field.text = self._from_python(bit)
  File "lxml.etree.pyx", line 921, in lxml.etree._Element.text.__set__ (src/lxml/lxml.etree.c:41264)
  File "apihelpers.pxi", line 652, in lxml.etree._setNodeText (src/lxml/lxml.etree.c:18755)
  File "apihelpers.pxi", line 1335, in lxml.etree._utf8 (src/lxml/lxml.etree.c:24545)
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/localdev/lib/python2.6/site-packages/django/core/management/base.py", line 222, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/vagrant/.virtualenvs/localdev/lib/python2.6/site-packages/django/core/management/base.py", line 255, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/.virtualenvs/localdev/lib/python2.6/site-packages/haystack/management/commands/rebuild_index.py", line 15, in handle
    call_command('update_index', **options)
  File "/home/vagrant/.virtualenvs/localdev/lib/python2.6/site-packages/django/core/management/__init__.py", line 161, in call_command
    return klass.execute(*args, **defaults)
  File "/home/vagrant/.virtualenvs/localdev/lib/python2.6/site-packages/django/core/management/base.py", line 255, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/.virtualenvs/localdev/lib/python2.6/site-packages/haystack/management/commands/update_index.py", line 184, in handle
    return super(Command, self).handle(*items, **options)
  File "/home/vagrant/.virtualenvs/localdev/lib/python2.6/site-packages/django/core/management/base.py", line 355, in handle
    label_output = self.handle_label(label, **options)
  File "/home/vagrant/.virtualenvs/localdev/lib/python2.6/site-packages/haystack/management/commands/update_index.py", line 210, in handle_label
    self.update_backend(label, using)
  File "/home/vagrant/.virtualenvs/localdev/lib/python2.6/site-packages/haystack/management/commands/update_index.py", line 256, in update_backend
    do_update(backend, index, qs, start, end, total, self.verbosity)
  File "/home/vagrant/.virtualenvs/localdev/lib/python2.6/site-packages/haystack/management/commands/update_index.py", line 78, in do_update
    backend.update(index, current_qs)
  File "/home/vagrant/.virtualenvs/localdev/lib/python2.6/site-packages/haystack/backends/solr_backend.py", line 66, in update
    self.conn.add(docs, commit=commit, boost=index.get_field_weights())
  File "/home/vagrant/.virtualenvs/localdev/lib/python2.6/site-packages/pysolr.py", line 740, in add
    message.append(self._build_doc(doc, boost=boost))
  File "/home/vagrant/.virtualenvs/localdev/lib/python2.6/site-packages/pysolr.py", line 696, in _build_doc
    field.text = self._from_python(bit)
  File "lxml.etree.pyx", line 921, in lxml.etree._Element.text.__set__ (src/lxml/lxml.etree.c:41264)
  File "apihelpers.pxi", line 652, in lxml.etree._setNodeText (src/lxml/lxml.etree.c:18755)
  File "apihelpers.pxi", line 1335, in lxml.etree._utf8 (src/lxml/lxml.etree.c:24545)
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
```

**Comment by acdha** [comment]
Closing as the upstream pysolr dependency shipped awhile back
