### ISSUE TITLE
update_index with multiple workers fails with traceback

### ISSUE THREAD

**Issue by comandrei** [django-haystack/django-haystack#860]
Environment: 
  Ubuntu 13.04
  Python 2.7.4
  Solr 4.4.0
  django==1.4.8
  django-haystack==2.0.0
  pysolr==3.1.0

Try to run python manage.py update_index -k 8 and you get a traceback similar to this:

``` python
Traceback (most recent call last):
  File "/home/user/.virtualenvs/ve/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 210, in handle_label
    self.update_backend(label, using)
  File "/home/user/.virtualenvs/ve/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 262, in update_backend
    pool.map(worker, ghetto_queue)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
TypeError: cannot concatenate 'str' and 'tuple' objects
```

Running update_index without any parameters works.

**Comment by viciu** [comment]
It is definitely still a problem (!). I experience the same issue when using -k parameter.

I experience it on mysql and elasticsearch 1.6.0

django-haystack==2.4.0

```
Traceback (most recent call last):
  File "/home/user/.virtualenvs/project/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 188, in handle_label
    self.update_backend(label, using)
  File "/home/user/.virtualenvs/project/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 239, in update_backend
    pool.map(worker, ghetto_queue)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
SerializationError
```

It looks like multiprocessing is splitting data between processes in a way, that causes (randomly?) different errors, like:

* SerializationError
* JSONDecodeError('Unterminated string starting at: line 1 column 64984 (char 64983)',)
* KeyError: 'items'

and more.

Setting batch size to some small amount reproduces this issue quick:

```
./manage.py rebuild_index -b5 -k2
```

**Comment by vqw** [comment]
I am using:
Django 1.8.11
Whoosh 2.7.4
Haystack 2.4.1
SQLite

I am doing either **update_index or rebuild_index** with **--workers 2** and **--verbosity 2**.
To be honest haystack is achieving 2 workers speed-up of around 500%. The indexing time with workers is very fast leading to assumption, that it **skips** some records
