### ISSUE TITLE
Whoosh backend: produces 'Exception: Called start_doc when already in a doc'

### ISSUE THREAD

**Issue by kamni** [django-haystack/django-haystack#952]
This error can occur whenever there is a previous error in updating the index for a single object, and the error continues for the rest of the updates (regardless if the other updates have errors).

There is already a try-except block in place that is supposed to allow updates to continue even when there is an error for a single object:

https://github.com/toastdriven/django-haystack/blob/master/haystack/backends/whoosh_backend.py#L190-204

 However the 'except' portion fails to reset the AsyncWriter, so it remains open and still thinks that it is 'in a doc'. This then creates the 'Called start_doc when already in a doc' error for every subsequent update.

I believe the issue is platform independent; however, I'm using:
- Python 2.7
- Whoosh 2.6.0
- Django-haystack 2.1.0
- Mac OS X 10.9

I've already fixed the issue in my own installation of haystack, and I'll be sending a pull request for the fix when I have tests and cleaned-up code in place.

---

Traceback excerpt (multiplied by several hundred entries):

Traceback (most recent call last):
  File "/Users/jay/.virtualenvs/plate/lib/python2.7/site-packages/haystack/backends/whoosh_backend.py", line 191, in update
    writer.update_document(**doc)
  File "/Users/jay/.virtualenvs/plate/lib/python2.7/site-packages/whoosh/writing.py", line 1027, in update_document
    self._record("update_document", args, kwargs)
  File "/Users/jay/.virtualenvs/plate/lib/python2.7/site-packages/whoosh/writing.py", line 1004, in _record
    getattr(self.writer, method)(_args, *_kwargs)
  File "/Users/jay/.virtualenvs/plate/lib/python2.7/site-packages/whoosh/writing.py", line 477, in update_document
    self.add_document(**fields)
  File "/Users/jay/.virtualenvs/plate/lib/python2.7/site-packages/whoosh/writing.py", line 732, in add_document
    perdocwriter.start_doc(docnum)
  File "/Users/jay/.virtualenvs/plate/lib/python2.7/site-packages/whoosh/codec/whoosh3.py", line 201, in start_doc
    raise Exception("Called start_doc when already in a doc")
Exception: Called start_doc when already in a doc

**Comment by esazhin** [comment]
trying to index a set of git repositories and having a lot of issues with file content storing/searching - one of them is this error in whoosh 2.5.7 The error appeared because i hit another exception matcher.block_min_length() > mcore.py return self._term_info.min_length() caused AttributeError: NoneType object has no atribure min_legth. Then from there it is giving the "Called start_doc when already in a doc" non stop.

**Comment by AbeHandler** [comment]
I am getting this error too

**Comment by EntilZha** [comment]
Ran into this issue as well. I was getting this stacktrace which initially caused the problem:

```
Traceback (most recent call last):
  File "util/build_whoosh.py", line 124, in <module>
    writer.add_document(title=title, content=text, id=title)
  File "/usr/local/lib/python3.5/site-packages/whoosh/writing.py", line 771, in add_document
    perdocwriter.add_vector_items(fieldname, field, vitems)
  File "/usr/local/lib/python3.5/site-packages/whoosh/codec/whoosh3.py", line 234, in add_vector_items
    vinfo = vpostwriter.finish_postings()
  File "/usr/local/lib/python3.5/site-packages/whoosh/codec/whoosh3.py", line 711, in finish_postings
    terminfo.add_block(self)
  File "/usr/local/lib/python3.5/site-packages/whoosh/codec/whoosh3.py", line 1146, in add_block
    self._minid = block.min_id()
  File "/usr/local/lib/python3.5/site-packages/whoosh/codec/whoosh3.py", line 839, in min_id
    return self._ids[0]
IndexError: list index out of range
```

**Comment by acdha** [comment]
Does anyone have a reproducible test which demonstrates this problem?

**Comment by EntilZha** [comment]
This may help since I was able to fix the problem in our code. Don't really have extra time to create a minimal example.

Whoosh index created here: https://github.com/Pinafore/qb/blob/eb899367a3c8234a4535239d3f4770149b12c23f/util/build_whoosh.py#L106-L128

It was breaking on `add_document` when `content` was equal to `"\n\n"` so I am going to guess it breaks on whitespace characters.

Pardon the messy (research) code, but hope that helps find the root cause.

**Comment by almostBeginner** [comment]
This is related to a datefield that has been indexed, but subsequently removed. I got the same error, and when I re-added those fields, it worked as normal.

**Comment by stevennic** [comment]
Hello, I have submitted a patch to Whoosh that may have addressed this issue. "Called start_doc when already in a doc" is raised when the previous add fails and exceptions were being absorbed. This leaves the Whoosh document writer in an unfinished state, preventing a subsequent `add` from completing successfully by complaining about the previous unfinished `add`. The fix ensures that the Whoosh document writer state is cleaned when exceptions are being absorbed, ensuring that subsequent `add`s can be successful. Please refer to the Fix above for more details. It is now in the master branch.
